// Automatically generated by odin 1.5.11 - do not edit
#include <float.h>
#include <R.h>
#include <Rmath.h>
#include <Rinternals.h>
#include <stdbool.h>
#include <R_ext/Rdynload.h>
#ifndef CINTERPOLTE_CINTERPOLATE_H_
#define CINTERPOLTE_CINTERPOLATE_H_

// Allow use from C++
#ifdef __cplusplus
extern "C" {
#endif

// There are only three functions in the interface; allocation,
// evaluation and freeing.

// Allocate an interpolation object.
//
//   type: The mode of interpolation. Must be one of "constant",
//       "linear" or "spline" (an R error is thrown if a different
//       value is given).
//
//   n: The number of `x` points to interpolate over
//
//   ny: the number of `y` points per `x` point.  This is 1 in the
//       case of zimple interpolation as used by Rs `interpolate()`
//
//   x: an array of `x` values of length `n`
//
//   y: an array of `ny` sets of `y` values.  This is in R's matrix
//       order (i.e., the first `n` values are the first series to
//       interpolate over).
//
//   fail_on_extrapolate: if true, when an extrapolation occurs throw
//       an error; if false return NA_REAL
//
//   auto_free: automatically clean up the interpolation object on
//       return to R. This uses `R_alloc` for allocations rather than
//       `Calloc` so freeing will always happen (even on error
//       elsewhere in the code). However, this prevents returning back
//       a pointer to R that will last longer than the call into C
//       code.
//
// The return value is an opaque pointer that can be passed through to
// `cinterpolate_eval` and `cinterpolate_free`
void *cinterpolate_alloc(const char *type, size_t n, size_t ny,
                         double *x, double *y, bool fail_on_extrapolate,
                         bool auto_free);

// Evaluate the interpolated function at a new `x` point.
//
//   x: A new, single, `x` point to interpolate `y` values to
//
//   obj: The interpolation object, as returned by `cinterpolate_alloc`
//
//   y: An array of length `ny` to store the interpolated values
//
// The return value is 0 if the interpolation is successful (with x
// lying within the range of values that the interpolation function
// supports), -1 otherwise
int cinterpolate_eval(double x, void *obj, double *y);

// Clean up all allocated memory
//
//   obj: The interpolation object, as returned by `cinterpolate_alloc`
void cinterpolate_free(void *obj);

#ifdef __cplusplus
}
#endif

#endif
typedef struct vaccine_simplified_internal {
  double *beta_set;
  double *D_0;
  int dim_beta_set;
  int dim_D;
  int dim_D_0;
  int dim_D_0_1;
  int dim_D_0_2;
  int dim_D_1;
  int dim_D_2;
  int dim_E;
  int dim_E_0;
  int dim_E_0_1;
  int dim_E_0_2;
  int dim_E_1;
  int dim_E_2;
  int dim_E_overall;
  int dim_gamma_vaccine;
  int dim_ICase;
  int dim_ICase_0;
  int dim_ICase_0_1;
  int dim_ICase_0_2;
  int dim_ICase_1;
  int dim_ICase_2;
  int dim_ICase_overall;
  int dim_IHosp;
  int dim_IHosp_0;
  int dim_IHosp_0_1;
  int dim_IHosp_0_2;
  int dim_IHosp_1;
  int dim_IHosp_2;
  int dim_IMild;
  int dim_IMild_0;
  int dim_IMild_0_1;
  int dim_IMild_0_2;
  int dim_IMild_1;
  int dim_IMild_2;
  int dim_IMild_overall;
  int dim_lambda;
  int dim_m;
  int dim_m_1;
  int dim_m_2;
  int dim_max_vaccine;
  int dim_mix_mat_set;
  int dim_mix_mat_set_1;
  int dim_mix_mat_set_12;
  int dim_mix_mat_set_2;
  int dim_mix_mat_set_3;
  int dim_N;
  int dim_pop_size;
  int dim_pr;
  int dim_prob_death_hosp;
  int dim_prob_death_hosp_1;
  int dim_prob_death_hosp_2;
  int dim_prob_hosp;
  int dim_prob_hosp_1;
  int dim_prob_hosp_2;
  int dim_R;
  int dim_R_0;
  int dim_R_0_1;
  int dim_R_0_2;
  int dim_R_1;
  int dim_R_2;
  int dim_R_overall;
  int dim_rel_infectiousness;
  int dim_rel_infectiousness_vaccinated;
  int dim_rel_infectiousness_vaccinated_1;
  int dim_rel_infectiousness_vaccinated_2;
  int dim_S;
  int dim_S_0;
  int dim_S_0_1;
  int dim_S_0_2;
  int dim_S_1;
  int dim_S_2;
  int dim_s_ij;
  int dim_s_ij_1;
  int dim_s_ij_2;
  int dim_S_overall;
  int dim_temp;
  int dim_temp_rel;
  int dim_temp_rel_1;
  int dim_temp_rel_2;
  int dim_tt_beta;
  int dim_tt_matrix;
  int dim_tt_vaccine;
  int dim_tt_vaccine_efficacy_infection;
  int dim_unvaccinated;
  int dim_vaccinated;
  int dim_vaccination_target;
  int dim_vaccination_target_mat;
  int dim_vaccination_target_mat_1;
  int dim_vaccination_target_mat_2;
  int dim_vaccine_coverage_mat;
  int dim_vaccine_coverage_mat_1;
  int dim_vaccine_coverage_mat_2;
  int dim_vaccine_efficacy_infection;
  int dim_vaccine_efficacy_infection_1;
  int dim_vaccine_efficacy_infection_12;
  int dim_vaccine_efficacy_infection_2;
  int dim_vaccine_efficacy_infection_3;
  int dim_vaccine_efficacy_infection_t;
  int dim_vaccine_efficacy_infection_t_1;
  int dim_vaccine_efficacy_infection_t_2;
  int dim_vaccine_target_vec;
  int dim_vr_temp;
  double *E_0;
  double gamma_E;
  double gamma_ICase;
  double gamma_IHosp;
  double gamma_IMild;
  double *gamma_vaccine;
  double *ICase_0;
  double *IHosp_0;
  double *IMild_0;
  double *initial_D;
  double *initial_E;
  double *initial_ICase;
  double *initial_IHosp;
  double *initial_IMild;
  double *initial_R;
  double *initial_S;
  void *interpolate_beta;
  void *interpolate_m;
  void *interpolate_mv;
  void *interpolate_vaccine_efficacy_infection_t;
  double *lambda;
  double *m;
  double *max_vaccine;
  double *mix_mat_set;
  int N_age;
  int N_prioritisation_steps;
  int N_vaccine;
  int offset_output_E_overall;
  int offset_output_ICase_overall;
  int offset_output_IMild_overall;
  int offset_output_N;
  int offset_output_R_overall;
  int offset_output_unvaccinated;
  int offset_output_vaccinated;
  int offset_variable_D;
  int offset_variable_ICase;
  int offset_variable_IHosp;
  int offset_variable_IMild;
  int offset_variable_R;
  double *pop_size;
  double *pr;
  double *prob_death_hosp;
  double *prob_hosp;
  double *R_0;
  double *rel_infectiousness;
  double *rel_infectiousness_vaccinated;
  double *S_0;
  double *s_ij;
  double *temp;
  double *temp_rel;
  double *tt_beta;
  double *tt_matrix;
  double *tt_vaccine;
  double *tt_vaccine_efficacy_infection;
  double *vaccination_target;
  double *vaccination_target_mat;
  double *vaccine_coverage_mat;
  double *vaccine_efficacy_infection;
  double *vaccine_efficacy_infection_t;
  double *vaccine_target_vec;
  double *vr_temp;
} vaccine_simplified_internal;
vaccine_simplified_internal* vaccine_simplified_get_internal(SEXP internal_p, int closed_error);
static void vaccine_simplified_finalise(SEXP internal_p);
SEXP vaccine_simplified_create(SEXP user);
void vaccine_simplified_initmod_desolve(void(* odeparms) (int *, double *));
SEXP vaccine_simplified_contents(SEXP internal_p);
SEXP vaccine_simplified_set_user(SEXP internal_p, SEXP user);
SEXP vaccine_simplified_set_initial(SEXP internal_p, SEXP t_ptr, SEXP state_ptr, SEXP vaccine_simplified_use_dde_ptr);
SEXP vaccine_simplified_metadata(SEXP internal_p);
SEXP vaccine_simplified_initial_conditions(SEXP internal_p, SEXP t_ptr);
void vaccine_simplified_rhs(vaccine_simplified_internal* internal, double t, double * state, double * dstatedt, double * output);
void vaccine_simplified_rhs_dde(size_t neq, double t, double * state, double * dstatedt, void * internal);
void vaccine_simplified_rhs_desolve(int * neq, double * t, double * state, double * dstatedt, double * output, int * np);
void vaccine_simplified_output_dde(size_t n_eq, double t, double * state, size_t n_output, double * output, void * internal_p);
SEXP vaccine_simplified_rhs_r(SEXP internal_p, SEXP t, SEXP state);
double user_get_scalar_double(SEXP user, const char *name,
                              double default_value, double min, double max);
int user_get_scalar_int(SEXP user, const char *name,
                        int default_value, double min, double max);
void user_check_values_double(double * value, size_t len,
                                  double min, double max, const char *name);
void user_check_values_int(int * value, size_t len,
                               double min, double max, const char *name);
void user_check_values(SEXP value, double min, double max,
                           const char *name);
SEXP user_list_element(SEXP list, const char *name);
void odin_set_dim(SEXP target, int rank, ...);
void* user_get_array_dim(SEXP user, bool is_integer, void * previous,
                         const char *name, int rank,
                         double min, double max, int *dest_dim);
void* user_get_array(SEXP user, bool is_integer, void * previous,
                     const char *name, double min, double max,
                     int rank, ...);
SEXP user_get_array_check(SEXP el, bool is_integer, const char *name,
                          double min, double max);
SEXP user_get_array_check_rank(SEXP user, const char *name, int rank,
                               bool required);
void interpolate_check_y(size_t nx, size_t ny, size_t i, const char *name_arg, const char *name_target);
double odin_sum1(double *x, size_t from, size_t to);
int odin_isum1(int *x, size_t from, size_t to);
double scalar_real(SEXP x, const char * name);
double odin_sum2(double* x, int from_i, int to_i, int from_j, int to_j, int dim_x_1);
double odin_sum3(double* x, int from_i, int to_i, int from_j, int to_j, int from_k, int to_k, int dim_x_1, int dim_x_12);
vaccine_simplified_internal* vaccine_simplified_get_internal(SEXP internal_p, int closed_error) {
  vaccine_simplified_internal *internal = NULL;
  if (TYPEOF(internal_p) != EXTPTRSXP) {
    Rf_error("Expected an external pointer");
  }
  internal = (vaccine_simplified_internal*) R_ExternalPtrAddr(internal_p);
  if (!internal && closed_error) {
    Rf_error("Pointer has been invalidated");
  }
  return internal;
}
void vaccine_simplified_finalise(SEXP internal_p) {
  vaccine_simplified_internal *internal = vaccine_simplified_get_internal(internal_p, 0);
  if (internal_p) {
    cinterpolate_free(internal->interpolate_beta);
    cinterpolate_free(internal->interpolate_m);
    cinterpolate_free(internal->interpolate_mv);
    cinterpolate_free(internal->interpolate_vaccine_efficacy_infection_t);
    internal->interpolate_beta = NULL;
    internal->interpolate_m = NULL;
    internal->interpolate_mv = NULL;
    internal->interpolate_vaccine_efficacy_infection_t = NULL;
    R_Free(internal->beta_set);
    R_Free(internal->D_0);
    R_Free(internal->E_0);
    R_Free(internal->gamma_vaccine);
    R_Free(internal->ICase_0);
    R_Free(internal->IHosp_0);
    R_Free(internal->IMild_0);
    R_Free(internal->initial_D);
    R_Free(internal->initial_E);
    R_Free(internal->initial_ICase);
    R_Free(internal->initial_IHosp);
    R_Free(internal->initial_IMild);
    R_Free(internal->initial_R);
    R_Free(internal->initial_S);
    R_Free(internal->lambda);
    R_Free(internal->m);
    R_Free(internal->max_vaccine);
    R_Free(internal->mix_mat_set);
    R_Free(internal->pop_size);
    R_Free(internal->pr);
    R_Free(internal->prob_death_hosp);
    R_Free(internal->prob_hosp);
    R_Free(internal->R_0);
    R_Free(internal->rel_infectiousness);
    R_Free(internal->rel_infectiousness_vaccinated);
    R_Free(internal->S_0);
    R_Free(internal->s_ij);
    R_Free(internal->temp);
    R_Free(internal->temp_rel);
    R_Free(internal->tt_beta);
    R_Free(internal->tt_matrix);
    R_Free(internal->tt_vaccine);
    R_Free(internal->tt_vaccine_efficacy_infection);
    R_Free(internal->vaccination_target);
    R_Free(internal->vaccination_target_mat);
    R_Free(internal->vaccine_coverage_mat);
    R_Free(internal->vaccine_efficacy_infection);
    R_Free(internal->vaccine_efficacy_infection_t);
    R_Free(internal->vaccine_target_vec);
    R_Free(internal->vr_temp);
    R_Free(internal);
    R_ClearExternalPtr(internal_p);
  }
}
SEXP vaccine_simplified_create(SEXP user) {
  vaccine_simplified_internal *internal = (vaccine_simplified_internal*) R_Calloc(1, vaccine_simplified_internal);
  internal->beta_set = NULL;
  internal->D_0 = NULL;
  internal->E_0 = NULL;
  internal->gamma_vaccine = NULL;
  internal->ICase_0 = NULL;
  internal->IHosp_0 = NULL;
  internal->IMild_0 = NULL;
  internal->initial_D = NULL;
  internal->initial_E = NULL;
  internal->initial_ICase = NULL;
  internal->initial_IHosp = NULL;
  internal->initial_IMild = NULL;
  internal->initial_R = NULL;
  internal->initial_S = NULL;
  internal->interpolate_m = NULL;
  internal->interpolate_vaccine_efficacy_infection_t = NULL;
  internal->lambda = NULL;
  internal->m = NULL;
  internal->max_vaccine = NULL;
  internal->mix_mat_set = NULL;
  internal->pop_size = NULL;
  internal->pr = NULL;
  internal->prob_death_hosp = NULL;
  internal->prob_hosp = NULL;
  internal->R_0 = NULL;
  internal->rel_infectiousness = NULL;
  internal->rel_infectiousness_vaccinated = NULL;
  internal->S_0 = NULL;
  internal->s_ij = NULL;
  internal->temp = NULL;
  internal->temp_rel = NULL;
  internal->tt_beta = NULL;
  internal->tt_matrix = NULL;
  internal->tt_vaccine = NULL;
  internal->tt_vaccine_efficacy_infection = NULL;
  internal->vaccination_target = NULL;
  internal->vaccination_target_mat = NULL;
  internal->vaccine_coverage_mat = NULL;
  internal->vaccine_efficacy_infection = NULL;
  internal->vaccine_efficacy_infection_t = NULL;
  internal->vaccine_target_vec = NULL;
  internal->vr_temp = NULL;
  internal->beta_set = NULL;
  internal->D_0 = NULL;
  internal->E_0 = NULL;
  internal->gamma_E = NA_REAL;
  internal->gamma_ICase = NA_REAL;
  internal->gamma_IHosp = NA_REAL;
  internal->gamma_IMild = NA_REAL;
  internal->gamma_vaccine = NULL;
  internal->ICase_0 = NULL;
  internal->IHosp_0 = NULL;
  internal->IMild_0 = NULL;
  internal->max_vaccine = NULL;
  internal->mix_mat_set = NULL;
  internal->N_age = NA_INTEGER;
  internal->N_prioritisation_steps = NA_INTEGER;
  internal->N_vaccine = NA_INTEGER;
  internal->prob_death_hosp = NULL;
  internal->prob_hosp = NULL;
  internal->R_0 = NULL;
  internal->rel_infectiousness = NULL;
  internal->rel_infectiousness_vaccinated = NULL;
  internal->S_0 = NULL;
  internal->tt_beta = NULL;
  internal->tt_matrix = NULL;
  internal->tt_vaccine = NULL;
  internal->tt_vaccine_efficacy_infection = NULL;
  internal->vaccine_coverage_mat = NULL;
  internal->vaccine_efficacy_infection = NULL;
  SEXP ptr = PROTECT(R_MakeExternalPtr(internal, R_NilValue, R_NilValue));
  R_RegisterCFinalizer(ptr, vaccine_simplified_finalise);
  UNPROTECT(1);
  return ptr;
}
static vaccine_simplified_internal *vaccine_simplified_internal_ds;
void vaccine_simplified_initmod_desolve(void(* odeparms) (int *, double *)) {
  static DL_FUNC get_desolve_gparms = NULL;
  if (get_desolve_gparms == NULL) {
    get_desolve_gparms =
      R_GetCCallable("deSolve", "get_deSolve_gparms");
  }
  vaccine_simplified_internal_ds = vaccine_simplified_get_internal(get_desolve_gparms(), 1);
}
SEXP vaccine_simplified_contents(SEXP internal_p) {
  vaccine_simplified_internal *internal = vaccine_simplified_get_internal(internal_p, 1);
  SEXP contents = PROTECT(allocVector(VECSXP, 165));
  SEXP beta_set = PROTECT(allocVector(REALSXP, internal->dim_beta_set));
  memcpy(REAL(beta_set), internal->beta_set, internal->dim_beta_set * sizeof(double));
  SET_VECTOR_ELT(contents, 0, beta_set);
  SEXP D_0 = PROTECT(allocVector(REALSXP, internal->dim_D_0));
  memcpy(REAL(D_0), internal->D_0, internal->dim_D_0 * sizeof(double));
  odin_set_dim(D_0, 2, internal->dim_D_0_1, internal->dim_D_0_2);
  SET_VECTOR_ELT(contents, 1, D_0);
  SET_VECTOR_ELT(contents, 2, ScalarInteger(internal->dim_beta_set));
  SET_VECTOR_ELT(contents, 3, ScalarInteger(internal->dim_D));
  SET_VECTOR_ELT(contents, 4, ScalarInteger(internal->dim_D_0));
  SET_VECTOR_ELT(contents, 5, ScalarInteger(internal->dim_D_0_1));
  SET_VECTOR_ELT(contents, 6, ScalarInteger(internal->dim_D_0_2));
  SET_VECTOR_ELT(contents, 7, ScalarInteger(internal->dim_D_1));
  SET_VECTOR_ELT(contents, 8, ScalarInteger(internal->dim_D_2));
  SET_VECTOR_ELT(contents, 9, ScalarInteger(internal->dim_E));
  SET_VECTOR_ELT(contents, 10, ScalarInteger(internal->dim_E_0));
  SET_VECTOR_ELT(contents, 11, ScalarInteger(internal->dim_E_0_1));
  SET_VECTOR_ELT(contents, 12, ScalarInteger(internal->dim_E_0_2));
  SET_VECTOR_ELT(contents, 13, ScalarInteger(internal->dim_E_1));
  SET_VECTOR_ELT(contents, 14, ScalarInteger(internal->dim_E_2));
  SET_VECTOR_ELT(contents, 15, ScalarInteger(internal->dim_E_overall));
  SET_VECTOR_ELT(contents, 16, ScalarInteger(internal->dim_gamma_vaccine));
  SET_VECTOR_ELT(contents, 17, ScalarInteger(internal->dim_ICase));
  SET_VECTOR_ELT(contents, 18, ScalarInteger(internal->dim_ICase_0));
  SET_VECTOR_ELT(contents, 19, ScalarInteger(internal->dim_ICase_0_1));
  SET_VECTOR_ELT(contents, 20, ScalarInteger(internal->dim_ICase_0_2));
  SET_VECTOR_ELT(contents, 21, ScalarInteger(internal->dim_ICase_1));
  SET_VECTOR_ELT(contents, 22, ScalarInteger(internal->dim_ICase_2));
  SET_VECTOR_ELT(contents, 23, ScalarInteger(internal->dim_ICase_overall));
  SET_VECTOR_ELT(contents, 24, ScalarInteger(internal->dim_IHosp));
  SET_VECTOR_ELT(contents, 25, ScalarInteger(internal->dim_IHosp_0));
  SET_VECTOR_ELT(contents, 26, ScalarInteger(internal->dim_IHosp_0_1));
  SET_VECTOR_ELT(contents, 27, ScalarInteger(internal->dim_IHosp_0_2));
  SET_VECTOR_ELT(contents, 28, ScalarInteger(internal->dim_IHosp_1));
  SET_VECTOR_ELT(contents, 29, ScalarInteger(internal->dim_IHosp_2));
  SET_VECTOR_ELT(contents, 30, ScalarInteger(internal->dim_IMild));
  SET_VECTOR_ELT(contents, 31, ScalarInteger(internal->dim_IMild_0));
  SET_VECTOR_ELT(contents, 32, ScalarInteger(internal->dim_IMild_0_1));
  SET_VECTOR_ELT(contents, 33, ScalarInteger(internal->dim_IMild_0_2));
  SET_VECTOR_ELT(contents, 34, ScalarInteger(internal->dim_IMild_1));
  SET_VECTOR_ELT(contents, 35, ScalarInteger(internal->dim_IMild_2));
  SET_VECTOR_ELT(contents, 36, ScalarInteger(internal->dim_IMild_overall));
  SET_VECTOR_ELT(contents, 37, ScalarInteger(internal->dim_lambda));
  SET_VECTOR_ELT(contents, 38, ScalarInteger(internal->dim_m));
  SET_VECTOR_ELT(contents, 39, ScalarInteger(internal->dim_m_1));
  SET_VECTOR_ELT(contents, 40, ScalarInteger(internal->dim_m_2));
  SET_VECTOR_ELT(contents, 41, ScalarInteger(internal->dim_max_vaccine));
  SET_VECTOR_ELT(contents, 42, ScalarInteger(internal->dim_mix_mat_set));
  SET_VECTOR_ELT(contents, 43, ScalarInteger(internal->dim_mix_mat_set_1));
  SET_VECTOR_ELT(contents, 44, ScalarInteger(internal->dim_mix_mat_set_12));
  SET_VECTOR_ELT(contents, 45, ScalarInteger(internal->dim_mix_mat_set_2));
  SET_VECTOR_ELT(contents, 46, ScalarInteger(internal->dim_mix_mat_set_3));
  SET_VECTOR_ELT(contents, 47, ScalarInteger(internal->dim_N));
  SET_VECTOR_ELT(contents, 48, ScalarInteger(internal->dim_pop_size));
  SET_VECTOR_ELT(contents, 49, ScalarInteger(internal->dim_pr));
  SET_VECTOR_ELT(contents, 50, ScalarInteger(internal->dim_prob_death_hosp));
  SET_VECTOR_ELT(contents, 51, ScalarInteger(internal->dim_prob_death_hosp_1));
  SET_VECTOR_ELT(contents, 52, ScalarInteger(internal->dim_prob_death_hosp_2));
  SET_VECTOR_ELT(contents, 53, ScalarInteger(internal->dim_prob_hosp));
  SET_VECTOR_ELT(contents, 54, ScalarInteger(internal->dim_prob_hosp_1));
  SET_VECTOR_ELT(contents, 55, ScalarInteger(internal->dim_prob_hosp_2));
  SET_VECTOR_ELT(contents, 56, ScalarInteger(internal->dim_R));
  SET_VECTOR_ELT(contents, 57, ScalarInteger(internal->dim_R_0));
  SET_VECTOR_ELT(contents, 58, ScalarInteger(internal->dim_R_0_1));
  SET_VECTOR_ELT(contents, 59, ScalarInteger(internal->dim_R_0_2));
  SET_VECTOR_ELT(contents, 60, ScalarInteger(internal->dim_R_1));
  SET_VECTOR_ELT(contents, 61, ScalarInteger(internal->dim_R_2));
  SET_VECTOR_ELT(contents, 62, ScalarInteger(internal->dim_R_overall));
  SET_VECTOR_ELT(contents, 63, ScalarInteger(internal->dim_rel_infectiousness));
  SET_VECTOR_ELT(contents, 64, ScalarInteger(internal->dim_rel_infectiousness_vaccinated));
  SET_VECTOR_ELT(contents, 65, ScalarInteger(internal->dim_rel_infectiousness_vaccinated_1));
  SET_VECTOR_ELT(contents, 66, ScalarInteger(internal->dim_rel_infectiousness_vaccinated_2));
  SET_VECTOR_ELT(contents, 67, ScalarInteger(internal->dim_S));
  SET_VECTOR_ELT(contents, 68, ScalarInteger(internal->dim_S_0));
  SET_VECTOR_ELT(contents, 69, ScalarInteger(internal->dim_S_0_1));
  SET_VECTOR_ELT(contents, 70, ScalarInteger(internal->dim_S_0_2));
  SET_VECTOR_ELT(contents, 71, ScalarInteger(internal->dim_S_1));
  SET_VECTOR_ELT(contents, 72, ScalarInteger(internal->dim_S_2));
  SET_VECTOR_ELT(contents, 73, ScalarInteger(internal->dim_s_ij));
  SET_VECTOR_ELT(contents, 74, ScalarInteger(internal->dim_s_ij_1));
  SET_VECTOR_ELT(contents, 75, ScalarInteger(internal->dim_s_ij_2));
  SET_VECTOR_ELT(contents, 76, ScalarInteger(internal->dim_S_overall));
  SET_VECTOR_ELT(contents, 77, ScalarInteger(internal->dim_temp));
  SET_VECTOR_ELT(contents, 78, ScalarInteger(internal->dim_temp_rel));
  SET_VECTOR_ELT(contents, 79, ScalarInteger(internal->dim_temp_rel_1));
  SET_VECTOR_ELT(contents, 80, ScalarInteger(internal->dim_temp_rel_2));
  SET_VECTOR_ELT(contents, 81, ScalarInteger(internal->dim_tt_beta));
  SET_VECTOR_ELT(contents, 82, ScalarInteger(internal->dim_tt_matrix));
  SET_VECTOR_ELT(contents, 83, ScalarInteger(internal->dim_tt_vaccine));
  SET_VECTOR_ELT(contents, 84, ScalarInteger(internal->dim_tt_vaccine_efficacy_infection));
  SET_VECTOR_ELT(contents, 85, ScalarInteger(internal->dim_unvaccinated));
  SET_VECTOR_ELT(contents, 86, ScalarInteger(internal->dim_vaccinated));
  SET_VECTOR_ELT(contents, 87, ScalarInteger(internal->dim_vaccination_target));
  SET_VECTOR_ELT(contents, 88, ScalarInteger(internal->dim_vaccination_target_mat));
  SET_VECTOR_ELT(contents, 89, ScalarInteger(internal->dim_vaccination_target_mat_1));
  SET_VECTOR_ELT(contents, 90, ScalarInteger(internal->dim_vaccination_target_mat_2));
  SET_VECTOR_ELT(contents, 91, ScalarInteger(internal->dim_vaccine_coverage_mat));
  SET_VECTOR_ELT(contents, 92, ScalarInteger(internal->dim_vaccine_coverage_mat_1));
  SET_VECTOR_ELT(contents, 93, ScalarInteger(internal->dim_vaccine_coverage_mat_2));
  SET_VECTOR_ELT(contents, 94, ScalarInteger(internal->dim_vaccine_efficacy_infection));
  SET_VECTOR_ELT(contents, 95, ScalarInteger(internal->dim_vaccine_efficacy_infection_1));
  SET_VECTOR_ELT(contents, 96, ScalarInteger(internal->dim_vaccine_efficacy_infection_12));
  SET_VECTOR_ELT(contents, 97, ScalarInteger(internal->dim_vaccine_efficacy_infection_2));
  SET_VECTOR_ELT(contents, 98, ScalarInteger(internal->dim_vaccine_efficacy_infection_3));
  SET_VECTOR_ELT(contents, 99, ScalarInteger(internal->dim_vaccine_efficacy_infection_t));
  SET_VECTOR_ELT(contents, 100, ScalarInteger(internal->dim_vaccine_efficacy_infection_t_1));
  SET_VECTOR_ELT(contents, 101, ScalarInteger(internal->dim_vaccine_efficacy_infection_t_2));
  SET_VECTOR_ELT(contents, 102, ScalarInteger(internal->dim_vaccine_target_vec));
  SET_VECTOR_ELT(contents, 103, ScalarInteger(internal->dim_vr_temp));
  SEXP E_0 = PROTECT(allocVector(REALSXP, internal->dim_E_0));
  memcpy(REAL(E_0), internal->E_0, internal->dim_E_0 * sizeof(double));
  odin_set_dim(E_0, 2, internal->dim_E_0_1, internal->dim_E_0_2);
  SET_VECTOR_ELT(contents, 104, E_0);
  SET_VECTOR_ELT(contents, 105, ScalarReal(internal->gamma_E));
  SET_VECTOR_ELT(contents, 106, ScalarReal(internal->gamma_ICase));
  SET_VECTOR_ELT(contents, 107, ScalarReal(internal->gamma_IHosp));
  SET_VECTOR_ELT(contents, 108, ScalarReal(internal->gamma_IMild));
  SEXP gamma_vaccine = PROTECT(allocVector(REALSXP, internal->dim_gamma_vaccine));
  memcpy(REAL(gamma_vaccine), internal->gamma_vaccine, internal->dim_gamma_vaccine * sizeof(double));
  SET_VECTOR_ELT(contents, 109, gamma_vaccine);
  SEXP ICase_0 = PROTECT(allocVector(REALSXP, internal->dim_ICase_0));
  memcpy(REAL(ICase_0), internal->ICase_0, internal->dim_ICase_0 * sizeof(double));
  odin_set_dim(ICase_0, 2, internal->dim_ICase_0_1, internal->dim_ICase_0_2);
  SET_VECTOR_ELT(contents, 110, ICase_0);
  SEXP IHosp_0 = PROTECT(allocVector(REALSXP, internal->dim_IHosp_0));
  memcpy(REAL(IHosp_0), internal->IHosp_0, internal->dim_IHosp_0 * sizeof(double));
  odin_set_dim(IHosp_0, 2, internal->dim_IHosp_0_1, internal->dim_IHosp_0_2);
  SET_VECTOR_ELT(contents, 111, IHosp_0);
  SEXP IMild_0 = PROTECT(allocVector(REALSXP, internal->dim_IMild_0));
  memcpy(REAL(IMild_0), internal->IMild_0, internal->dim_IMild_0 * sizeof(double));
  odin_set_dim(IMild_0, 2, internal->dim_IMild_0_1, internal->dim_IMild_0_2);
  SET_VECTOR_ELT(contents, 112, IMild_0);
  SEXP initial_D = PROTECT(allocVector(REALSXP, internal->dim_D));
  memcpy(REAL(initial_D), internal->initial_D, internal->dim_D * sizeof(double));
  odin_set_dim(initial_D, 2, internal->dim_D_1, internal->dim_D_2);
  SET_VECTOR_ELT(contents, 113, initial_D);
  SEXP initial_E = PROTECT(allocVector(REALSXP, internal->dim_E));
  memcpy(REAL(initial_E), internal->initial_E, internal->dim_E * sizeof(double));
  odin_set_dim(initial_E, 2, internal->dim_E_1, internal->dim_E_2);
  SET_VECTOR_ELT(contents, 114, initial_E);
  SEXP initial_ICase = PROTECT(allocVector(REALSXP, internal->dim_ICase));
  memcpy(REAL(initial_ICase), internal->initial_ICase, internal->dim_ICase * sizeof(double));
  odin_set_dim(initial_ICase, 2, internal->dim_ICase_1, internal->dim_ICase_2);
  SET_VECTOR_ELT(contents, 115, initial_ICase);
  SEXP initial_IHosp = PROTECT(allocVector(REALSXP, internal->dim_IHosp));
  memcpy(REAL(initial_IHosp), internal->initial_IHosp, internal->dim_IHosp * sizeof(double));
  odin_set_dim(initial_IHosp, 2, internal->dim_IHosp_1, internal->dim_IHosp_2);
  SET_VECTOR_ELT(contents, 116, initial_IHosp);
  SEXP initial_IMild = PROTECT(allocVector(REALSXP, internal->dim_IMild));
  memcpy(REAL(initial_IMild), internal->initial_IMild, internal->dim_IMild * sizeof(double));
  odin_set_dim(initial_IMild, 2, internal->dim_IMild_1, internal->dim_IMild_2);
  SET_VECTOR_ELT(contents, 117, initial_IMild);
  SEXP initial_R = PROTECT(allocVector(REALSXP, internal->dim_R));
  memcpy(REAL(initial_R), internal->initial_R, internal->dim_R * sizeof(double));
  odin_set_dim(initial_R, 2, internal->dim_R_1, internal->dim_R_2);
  SET_VECTOR_ELT(contents, 118, initial_R);
  SEXP initial_S = PROTECT(allocVector(REALSXP, internal->dim_S));
  memcpy(REAL(initial_S), internal->initial_S, internal->dim_S * sizeof(double));
  odin_set_dim(initial_S, 2, internal->dim_S_1, internal->dim_S_2);
  SET_VECTOR_ELT(contents, 119, initial_S);
  SEXP lambda = PROTECT(allocVector(REALSXP, internal->dim_lambda));
  memcpy(REAL(lambda), internal->lambda, internal->dim_lambda * sizeof(double));
  SET_VECTOR_ELT(contents, 124, lambda);
  SEXP m = PROTECT(allocVector(REALSXP, internal->dim_m));
  memcpy(REAL(m), internal->m, internal->dim_m * sizeof(double));
  odin_set_dim(m, 2, internal->dim_m_1, internal->dim_m_2);
  SET_VECTOR_ELT(contents, 125, m);
  SEXP max_vaccine = PROTECT(allocVector(REALSXP, internal->dim_max_vaccine));
  memcpy(REAL(max_vaccine), internal->max_vaccine, internal->dim_max_vaccine * sizeof(double));
  SET_VECTOR_ELT(contents, 126, max_vaccine);
  SEXP mix_mat_set = PROTECT(allocVector(REALSXP, internal->dim_mix_mat_set));
  memcpy(REAL(mix_mat_set), internal->mix_mat_set, internal->dim_mix_mat_set * sizeof(double));
  odin_set_dim(mix_mat_set, 3, internal->dim_mix_mat_set_1, internal->dim_mix_mat_set_2, internal->dim_mix_mat_set_3);
  SET_VECTOR_ELT(contents, 127, mix_mat_set);
  SET_VECTOR_ELT(contents, 128, ScalarInteger(internal->N_age));
  SET_VECTOR_ELT(contents, 129, ScalarInteger(internal->N_prioritisation_steps));
  SET_VECTOR_ELT(contents, 130, ScalarInteger(internal->N_vaccine));
  SET_VECTOR_ELT(contents, 131, ScalarInteger(internal->offset_output_E_overall));
  SET_VECTOR_ELT(contents, 132, ScalarInteger(internal->offset_output_ICase_overall));
  SET_VECTOR_ELT(contents, 133, ScalarInteger(internal->offset_output_IMild_overall));
  SET_VECTOR_ELT(contents, 134, ScalarInteger(internal->offset_output_N));
  SET_VECTOR_ELT(contents, 135, ScalarInteger(internal->offset_output_R_overall));
  SET_VECTOR_ELT(contents, 136, ScalarInteger(internal->offset_output_unvaccinated));
  SET_VECTOR_ELT(contents, 137, ScalarInteger(internal->offset_output_vaccinated));
  SET_VECTOR_ELT(contents, 138, ScalarInteger(internal->offset_variable_D));
  SET_VECTOR_ELT(contents, 139, ScalarInteger(internal->offset_variable_ICase));
  SET_VECTOR_ELT(contents, 140, ScalarInteger(internal->offset_variable_IHosp));
  SET_VECTOR_ELT(contents, 141, ScalarInteger(internal->offset_variable_IMild));
  SET_VECTOR_ELT(contents, 142, ScalarInteger(internal->offset_variable_R));
  SEXP pop_size = PROTECT(allocVector(REALSXP, internal->dim_pop_size));
  memcpy(REAL(pop_size), internal->pop_size, internal->dim_pop_size * sizeof(double));
  SET_VECTOR_ELT(contents, 143, pop_size);
  SEXP pr = PROTECT(allocVector(REALSXP, internal->dim_pr));
  memcpy(REAL(pr), internal->pr, internal->dim_pr * sizeof(double));
  SET_VECTOR_ELT(contents, 144, pr);
  SEXP prob_death_hosp = PROTECT(allocVector(REALSXP, internal->dim_prob_death_hosp));
  memcpy(REAL(prob_death_hosp), internal->prob_death_hosp, internal->dim_prob_death_hosp * sizeof(double));
  odin_set_dim(prob_death_hosp, 2, internal->dim_prob_death_hosp_1, internal->dim_prob_death_hosp_2);
  SET_VECTOR_ELT(contents, 145, prob_death_hosp);
  SEXP prob_hosp = PROTECT(allocVector(REALSXP, internal->dim_prob_hosp));
  memcpy(REAL(prob_hosp), internal->prob_hosp, internal->dim_prob_hosp * sizeof(double));
  odin_set_dim(prob_hosp, 2, internal->dim_prob_hosp_1, internal->dim_prob_hosp_2);
  SET_VECTOR_ELT(contents, 146, prob_hosp);
  SEXP R_0 = PROTECT(allocVector(REALSXP, internal->dim_R_0));
  memcpy(REAL(R_0), internal->R_0, internal->dim_R_0 * sizeof(double));
  odin_set_dim(R_0, 2, internal->dim_R_0_1, internal->dim_R_0_2);
  SET_VECTOR_ELT(contents, 147, R_0);
  SEXP rel_infectiousness = PROTECT(allocVector(REALSXP, internal->dim_rel_infectiousness));
  memcpy(REAL(rel_infectiousness), internal->rel_infectiousness, internal->dim_rel_infectiousness * sizeof(double));
  SET_VECTOR_ELT(contents, 148, rel_infectiousness);
  SEXP rel_infectiousness_vaccinated = PROTECT(allocVector(REALSXP, internal->dim_rel_infectiousness_vaccinated));
  memcpy(REAL(rel_infectiousness_vaccinated), internal->rel_infectiousness_vaccinated, internal->dim_rel_infectiousness_vaccinated * sizeof(double));
  odin_set_dim(rel_infectiousness_vaccinated, 2, internal->dim_rel_infectiousness_vaccinated_1, internal->dim_rel_infectiousness_vaccinated_2);
  SET_VECTOR_ELT(contents, 149, rel_infectiousness_vaccinated);
  SEXP S_0 = PROTECT(allocVector(REALSXP, internal->dim_S_0));
  memcpy(REAL(S_0), internal->S_0, internal->dim_S_0 * sizeof(double));
  odin_set_dim(S_0, 2, internal->dim_S_0_1, internal->dim_S_0_2);
  SET_VECTOR_ELT(contents, 150, S_0);
  SEXP s_ij = PROTECT(allocVector(REALSXP, internal->dim_s_ij));
  memcpy(REAL(s_ij), internal->s_ij, internal->dim_s_ij * sizeof(double));
  odin_set_dim(s_ij, 2, internal->dim_s_ij_1, internal->dim_s_ij_2);
  SET_VECTOR_ELT(contents, 151, s_ij);
  SEXP temp = PROTECT(allocVector(REALSXP, internal->dim_temp));
  memcpy(REAL(temp), internal->temp, internal->dim_temp * sizeof(double));
  SET_VECTOR_ELT(contents, 152, temp);
  SEXP temp_rel = PROTECT(allocVector(REALSXP, internal->dim_temp_rel));
  memcpy(REAL(temp_rel), internal->temp_rel, internal->dim_temp_rel * sizeof(double));
  odin_set_dim(temp_rel, 2, internal->dim_temp_rel_1, internal->dim_temp_rel_2);
  SET_VECTOR_ELT(contents, 153, temp_rel);
  SEXP tt_beta = PROTECT(allocVector(REALSXP, internal->dim_tt_beta));
  memcpy(REAL(tt_beta), internal->tt_beta, internal->dim_tt_beta * sizeof(double));
  SET_VECTOR_ELT(contents, 154, tt_beta);
  SEXP tt_matrix = PROTECT(allocVector(REALSXP, internal->dim_tt_matrix));
  memcpy(REAL(tt_matrix), internal->tt_matrix, internal->dim_tt_matrix * sizeof(double));
  SET_VECTOR_ELT(contents, 155, tt_matrix);
  SEXP tt_vaccine = PROTECT(allocVector(REALSXP, internal->dim_tt_vaccine));
  memcpy(REAL(tt_vaccine), internal->tt_vaccine, internal->dim_tt_vaccine * sizeof(double));
  SET_VECTOR_ELT(contents, 156, tt_vaccine);
  SEXP tt_vaccine_efficacy_infection = PROTECT(allocVector(REALSXP, internal->dim_tt_vaccine_efficacy_infection));
  memcpy(REAL(tt_vaccine_efficacy_infection), internal->tt_vaccine_efficacy_infection, internal->dim_tt_vaccine_efficacy_infection * sizeof(double));
  SET_VECTOR_ELT(contents, 157, tt_vaccine_efficacy_infection);
  SEXP vaccination_target = PROTECT(allocVector(REALSXP, internal->dim_vaccination_target));
  memcpy(REAL(vaccination_target), internal->vaccination_target, internal->dim_vaccination_target * sizeof(double));
  SET_VECTOR_ELT(contents, 158, vaccination_target);
  SEXP vaccination_target_mat = PROTECT(allocVector(REALSXP, internal->dim_vaccination_target_mat));
  memcpy(REAL(vaccination_target_mat), internal->vaccination_target_mat, internal->dim_vaccination_target_mat * sizeof(double));
  odin_set_dim(vaccination_target_mat, 2, internal->dim_vaccination_target_mat_1, internal->dim_vaccination_target_mat_2);
  SET_VECTOR_ELT(contents, 159, vaccination_target_mat);
  SEXP vaccine_coverage_mat = PROTECT(allocVector(REALSXP, internal->dim_vaccine_coverage_mat));
  memcpy(REAL(vaccine_coverage_mat), internal->vaccine_coverage_mat, internal->dim_vaccine_coverage_mat * sizeof(double));
  odin_set_dim(vaccine_coverage_mat, 2, internal->dim_vaccine_coverage_mat_1, internal->dim_vaccine_coverage_mat_2);
  SET_VECTOR_ELT(contents, 160, vaccine_coverage_mat);
  SEXP vaccine_efficacy_infection = PROTECT(allocVector(REALSXP, internal->dim_vaccine_efficacy_infection));
  memcpy(REAL(vaccine_efficacy_infection), internal->vaccine_efficacy_infection, internal->dim_vaccine_efficacy_infection * sizeof(double));
  odin_set_dim(vaccine_efficacy_infection, 3, internal->dim_vaccine_efficacy_infection_1, internal->dim_vaccine_efficacy_infection_2, internal->dim_vaccine_efficacy_infection_3);
  SET_VECTOR_ELT(contents, 161, vaccine_efficacy_infection);
  SEXP vaccine_efficacy_infection_t = PROTECT(allocVector(REALSXP, internal->dim_vaccine_efficacy_infection_t));
  memcpy(REAL(vaccine_efficacy_infection_t), internal->vaccine_efficacy_infection_t, internal->dim_vaccine_efficacy_infection_t * sizeof(double));
  odin_set_dim(vaccine_efficacy_infection_t, 2, internal->dim_vaccine_efficacy_infection_t_1, internal->dim_vaccine_efficacy_infection_t_2);
  SET_VECTOR_ELT(contents, 162, vaccine_efficacy_infection_t);
  SEXP vaccine_target_vec = PROTECT(allocVector(REALSXP, internal->dim_vaccine_target_vec));
  memcpy(REAL(vaccine_target_vec), internal->vaccine_target_vec, internal->dim_vaccine_target_vec * sizeof(double));
  SET_VECTOR_ELT(contents, 163, vaccine_target_vec);
  SEXP vr_temp = PROTECT(allocVector(REALSXP, internal->dim_vr_temp));
  memcpy(REAL(vr_temp), internal->vr_temp, internal->dim_vr_temp * sizeof(double));
  SET_VECTOR_ELT(contents, 164, vr_temp);
  SEXP nms = PROTECT(allocVector(STRSXP, 165));
  SET_STRING_ELT(nms, 0, mkChar("beta_set"));
  SET_STRING_ELT(nms, 1, mkChar("D_0"));
  SET_STRING_ELT(nms, 2, mkChar("dim_beta_set"));
  SET_STRING_ELT(nms, 3, mkChar("dim_D"));
  SET_STRING_ELT(nms, 4, mkChar("dim_D_0"));
  SET_STRING_ELT(nms, 5, mkChar("dim_D_0_1"));
  SET_STRING_ELT(nms, 6, mkChar("dim_D_0_2"));
  SET_STRING_ELT(nms, 7, mkChar("dim_D_1"));
  SET_STRING_ELT(nms, 8, mkChar("dim_D_2"));
  SET_STRING_ELT(nms, 9, mkChar("dim_E"));
  SET_STRING_ELT(nms, 10, mkChar("dim_E_0"));
  SET_STRING_ELT(nms, 11, mkChar("dim_E_0_1"));
  SET_STRING_ELT(nms, 12, mkChar("dim_E_0_2"));
  SET_STRING_ELT(nms, 13, mkChar("dim_E_1"));
  SET_STRING_ELT(nms, 14, mkChar("dim_E_2"));
  SET_STRING_ELT(nms, 15, mkChar("dim_E_overall"));
  SET_STRING_ELT(nms, 16, mkChar("dim_gamma_vaccine"));
  SET_STRING_ELT(nms, 17, mkChar("dim_ICase"));
  SET_STRING_ELT(nms, 18, mkChar("dim_ICase_0"));
  SET_STRING_ELT(nms, 19, mkChar("dim_ICase_0_1"));
  SET_STRING_ELT(nms, 20, mkChar("dim_ICase_0_2"));
  SET_STRING_ELT(nms, 21, mkChar("dim_ICase_1"));
  SET_STRING_ELT(nms, 22, mkChar("dim_ICase_2"));
  SET_STRING_ELT(nms, 23, mkChar("dim_ICase_overall"));
  SET_STRING_ELT(nms, 24, mkChar("dim_IHosp"));
  SET_STRING_ELT(nms, 25, mkChar("dim_IHosp_0"));
  SET_STRING_ELT(nms, 26, mkChar("dim_IHosp_0_1"));
  SET_STRING_ELT(nms, 27, mkChar("dim_IHosp_0_2"));
  SET_STRING_ELT(nms, 28, mkChar("dim_IHosp_1"));
  SET_STRING_ELT(nms, 29, mkChar("dim_IHosp_2"));
  SET_STRING_ELT(nms, 30, mkChar("dim_IMild"));
  SET_STRING_ELT(nms, 31, mkChar("dim_IMild_0"));
  SET_STRING_ELT(nms, 32, mkChar("dim_IMild_0_1"));
  SET_STRING_ELT(nms, 33, mkChar("dim_IMild_0_2"));
  SET_STRING_ELT(nms, 34, mkChar("dim_IMild_1"));
  SET_STRING_ELT(nms, 35, mkChar("dim_IMild_2"));
  SET_STRING_ELT(nms, 36, mkChar("dim_IMild_overall"));
  SET_STRING_ELT(nms, 37, mkChar("dim_lambda"));
  SET_STRING_ELT(nms, 38, mkChar("dim_m"));
  SET_STRING_ELT(nms, 39, mkChar("dim_m_1"));
  SET_STRING_ELT(nms, 40, mkChar("dim_m_2"));
  SET_STRING_ELT(nms, 41, mkChar("dim_max_vaccine"));
  SET_STRING_ELT(nms, 42, mkChar("dim_mix_mat_set"));
  SET_STRING_ELT(nms, 43, mkChar("dim_mix_mat_set_1"));
  SET_STRING_ELT(nms, 44, mkChar("dim_mix_mat_set_12"));
  SET_STRING_ELT(nms, 45, mkChar("dim_mix_mat_set_2"));
  SET_STRING_ELT(nms, 46, mkChar("dim_mix_mat_set_3"));
  SET_STRING_ELT(nms, 47, mkChar("dim_N"));
  SET_STRING_ELT(nms, 48, mkChar("dim_pop_size"));
  SET_STRING_ELT(nms, 49, mkChar("dim_pr"));
  SET_STRING_ELT(nms, 50, mkChar("dim_prob_death_hosp"));
  SET_STRING_ELT(nms, 51, mkChar("dim_prob_death_hosp_1"));
  SET_STRING_ELT(nms, 52, mkChar("dim_prob_death_hosp_2"));
  SET_STRING_ELT(nms, 53, mkChar("dim_prob_hosp"));
  SET_STRING_ELT(nms, 54, mkChar("dim_prob_hosp_1"));
  SET_STRING_ELT(nms, 55, mkChar("dim_prob_hosp_2"));
  SET_STRING_ELT(nms, 56, mkChar("dim_R"));
  SET_STRING_ELT(nms, 57, mkChar("dim_R_0"));
  SET_STRING_ELT(nms, 58, mkChar("dim_R_0_1"));
  SET_STRING_ELT(nms, 59, mkChar("dim_R_0_2"));
  SET_STRING_ELT(nms, 60, mkChar("dim_R_1"));
  SET_STRING_ELT(nms, 61, mkChar("dim_R_2"));
  SET_STRING_ELT(nms, 62, mkChar("dim_R_overall"));
  SET_STRING_ELT(nms, 63, mkChar("dim_rel_infectiousness"));
  SET_STRING_ELT(nms, 64, mkChar("dim_rel_infectiousness_vaccinated"));
  SET_STRING_ELT(nms, 65, mkChar("dim_rel_infectiousness_vaccinated_1"));
  SET_STRING_ELT(nms, 66, mkChar("dim_rel_infectiousness_vaccinated_2"));
  SET_STRING_ELT(nms, 67, mkChar("dim_S"));
  SET_STRING_ELT(nms, 68, mkChar("dim_S_0"));
  SET_STRING_ELT(nms, 69, mkChar("dim_S_0_1"));
  SET_STRING_ELT(nms, 70, mkChar("dim_S_0_2"));
  SET_STRING_ELT(nms, 71, mkChar("dim_S_1"));
  SET_STRING_ELT(nms, 72, mkChar("dim_S_2"));
  SET_STRING_ELT(nms, 73, mkChar("dim_s_ij"));
  SET_STRING_ELT(nms, 74, mkChar("dim_s_ij_1"));
  SET_STRING_ELT(nms, 75, mkChar("dim_s_ij_2"));
  SET_STRING_ELT(nms, 76, mkChar("dim_S_overall"));
  SET_STRING_ELT(nms, 77, mkChar("dim_temp"));
  SET_STRING_ELT(nms, 78, mkChar("dim_temp_rel"));
  SET_STRING_ELT(nms, 79, mkChar("dim_temp_rel_1"));
  SET_STRING_ELT(nms, 80, mkChar("dim_temp_rel_2"));
  SET_STRING_ELT(nms, 81, mkChar("dim_tt_beta"));
  SET_STRING_ELT(nms, 82, mkChar("dim_tt_matrix"));
  SET_STRING_ELT(nms, 83, mkChar("dim_tt_vaccine"));
  SET_STRING_ELT(nms, 84, mkChar("dim_tt_vaccine_efficacy_infection"));
  SET_STRING_ELT(nms, 85, mkChar("dim_unvaccinated"));
  SET_STRING_ELT(nms, 86, mkChar("dim_vaccinated"));
  SET_STRING_ELT(nms, 87, mkChar("dim_vaccination_target"));
  SET_STRING_ELT(nms, 88, mkChar("dim_vaccination_target_mat"));
  SET_STRING_ELT(nms, 89, mkChar("dim_vaccination_target_mat_1"));
  SET_STRING_ELT(nms, 90, mkChar("dim_vaccination_target_mat_2"));
  SET_STRING_ELT(nms, 91, mkChar("dim_vaccine_coverage_mat"));
  SET_STRING_ELT(nms, 92, mkChar("dim_vaccine_coverage_mat_1"));
  SET_STRING_ELT(nms, 93, mkChar("dim_vaccine_coverage_mat_2"));
  SET_STRING_ELT(nms, 94, mkChar("dim_vaccine_efficacy_infection"));
  SET_STRING_ELT(nms, 95, mkChar("dim_vaccine_efficacy_infection_1"));
  SET_STRING_ELT(nms, 96, mkChar("dim_vaccine_efficacy_infection_12"));
  SET_STRING_ELT(nms, 97, mkChar("dim_vaccine_efficacy_infection_2"));
  SET_STRING_ELT(nms, 98, mkChar("dim_vaccine_efficacy_infection_3"));
  SET_STRING_ELT(nms, 99, mkChar("dim_vaccine_efficacy_infection_t"));
  SET_STRING_ELT(nms, 100, mkChar("dim_vaccine_efficacy_infection_t_1"));
  SET_STRING_ELT(nms, 101, mkChar("dim_vaccine_efficacy_infection_t_2"));
  SET_STRING_ELT(nms, 102, mkChar("dim_vaccine_target_vec"));
  SET_STRING_ELT(nms, 103, mkChar("dim_vr_temp"));
  SET_STRING_ELT(nms, 104, mkChar("E_0"));
  SET_STRING_ELT(nms, 105, mkChar("gamma_E"));
  SET_STRING_ELT(nms, 106, mkChar("gamma_ICase"));
  SET_STRING_ELT(nms, 107, mkChar("gamma_IHosp"));
  SET_STRING_ELT(nms, 108, mkChar("gamma_IMild"));
  SET_STRING_ELT(nms, 109, mkChar("gamma_vaccine"));
  SET_STRING_ELT(nms, 110, mkChar("ICase_0"));
  SET_STRING_ELT(nms, 111, mkChar("IHosp_0"));
  SET_STRING_ELT(nms, 112, mkChar("IMild_0"));
  SET_STRING_ELT(nms, 113, mkChar("initial_D"));
  SET_STRING_ELT(nms, 114, mkChar("initial_E"));
  SET_STRING_ELT(nms, 115, mkChar("initial_ICase"));
  SET_STRING_ELT(nms, 116, mkChar("initial_IHosp"));
  SET_STRING_ELT(nms, 117, mkChar("initial_IMild"));
  SET_STRING_ELT(nms, 118, mkChar("initial_R"));
  SET_STRING_ELT(nms, 119, mkChar("initial_S"));
  SET_STRING_ELT(nms, 120, mkChar("interpolate_beta"));
  SET_STRING_ELT(nms, 121, mkChar("interpolate_m"));
  SET_STRING_ELT(nms, 122, mkChar("interpolate_mv"));
  SET_STRING_ELT(nms, 123, mkChar("interpolate_vaccine_efficacy_infection_t"));
  SET_STRING_ELT(nms, 124, mkChar("lambda"));
  SET_STRING_ELT(nms, 125, mkChar("m"));
  SET_STRING_ELT(nms, 126, mkChar("max_vaccine"));
  SET_STRING_ELT(nms, 127, mkChar("mix_mat_set"));
  SET_STRING_ELT(nms, 128, mkChar("N_age"));
  SET_STRING_ELT(nms, 129, mkChar("N_prioritisation_steps"));
  SET_STRING_ELT(nms, 130, mkChar("N_vaccine"));
  SET_STRING_ELT(nms, 131, mkChar("offset_output_E_overall"));
  SET_STRING_ELT(nms, 132, mkChar("offset_output_ICase_overall"));
  SET_STRING_ELT(nms, 133, mkChar("offset_output_IMild_overall"));
  SET_STRING_ELT(nms, 134, mkChar("offset_output_N"));
  SET_STRING_ELT(nms, 135, mkChar("offset_output_R_overall"));
  SET_STRING_ELT(nms, 136, mkChar("offset_output_unvaccinated"));
  SET_STRING_ELT(nms, 137, mkChar("offset_output_vaccinated"));
  SET_STRING_ELT(nms, 138, mkChar("offset_variable_D"));
  SET_STRING_ELT(nms, 139, mkChar("offset_variable_ICase"));
  SET_STRING_ELT(nms, 140, mkChar("offset_variable_IHosp"));
  SET_STRING_ELT(nms, 141, mkChar("offset_variable_IMild"));
  SET_STRING_ELT(nms, 142, mkChar("offset_variable_R"));
  SET_STRING_ELT(nms, 143, mkChar("pop_size"));
  SET_STRING_ELT(nms, 144, mkChar("pr"));
  SET_STRING_ELT(nms, 145, mkChar("prob_death_hosp"));
  SET_STRING_ELT(nms, 146, mkChar("prob_hosp"));
  SET_STRING_ELT(nms, 147, mkChar("R_0"));
  SET_STRING_ELT(nms, 148, mkChar("rel_infectiousness"));
  SET_STRING_ELT(nms, 149, mkChar("rel_infectiousness_vaccinated"));
  SET_STRING_ELT(nms, 150, mkChar("S_0"));
  SET_STRING_ELT(nms, 151, mkChar("s_ij"));
  SET_STRING_ELT(nms, 152, mkChar("temp"));
  SET_STRING_ELT(nms, 153, mkChar("temp_rel"));
  SET_STRING_ELT(nms, 154, mkChar("tt_beta"));
  SET_STRING_ELT(nms, 155, mkChar("tt_matrix"));
  SET_STRING_ELT(nms, 156, mkChar("tt_vaccine"));
  SET_STRING_ELT(nms, 157, mkChar("tt_vaccine_efficacy_infection"));
  SET_STRING_ELT(nms, 158, mkChar("vaccination_target"));
  SET_STRING_ELT(nms, 159, mkChar("vaccination_target_mat"));
  SET_STRING_ELT(nms, 160, mkChar("vaccine_coverage_mat"));
  SET_STRING_ELT(nms, 161, mkChar("vaccine_efficacy_infection"));
  SET_STRING_ELT(nms, 162, mkChar("vaccine_efficacy_infection_t"));
  SET_STRING_ELT(nms, 163, mkChar("vaccine_target_vec"));
  SET_STRING_ELT(nms, 164, mkChar("vr_temp"));
  setAttrib(contents, R_NamesSymbol, nms);
  UNPROTECT(42);
  return contents;
}
SEXP vaccine_simplified_set_user(SEXP internal_p, SEXP user) {
  vaccine_simplified_internal *internal = vaccine_simplified_get_internal(internal_p, 1);
  internal->gamma_E = user_get_scalar_double(user, "gamma_E", internal->gamma_E, NA_REAL, NA_REAL);
  internal->gamma_ICase = user_get_scalar_double(user, "gamma_ICase", internal->gamma_ICase, NA_REAL, NA_REAL);
  internal->gamma_IHosp = user_get_scalar_double(user, "gamma_IHosp", internal->gamma_IHosp, NA_REAL, NA_REAL);
  internal->gamma_IMild = user_get_scalar_double(user, "gamma_IMild", internal->gamma_IMild, NA_REAL, NA_REAL);
  internal->N_age = user_get_scalar_int(user, "N_age", internal->N_age, NA_REAL, NA_REAL);
  internal->N_prioritisation_steps = user_get_scalar_int(user, "N_prioritisation_steps", internal->N_prioritisation_steps, NA_REAL, NA_REAL);
  internal->N_vaccine = user_get_scalar_int(user, "N_vaccine", internal->N_vaccine, NA_REAL, NA_REAL);
  internal->tt_beta = (double*) user_get_array_dim(user, false, internal->tt_beta, "tt_beta", 1, NA_REAL, NA_REAL, &internal->dim_tt_beta);
  internal->tt_matrix = (double*) user_get_array_dim(user, false, internal->tt_matrix, "tt_matrix", 1, NA_REAL, NA_REAL, &internal->dim_tt_matrix);
  internal->tt_vaccine = (double*) user_get_array_dim(user, false, internal->tt_vaccine, "tt_vaccine", 1, NA_REAL, NA_REAL, &internal->dim_tt_vaccine);
  internal->tt_vaccine_efficacy_infection = (double*) user_get_array_dim(user, false, internal->tt_vaccine_efficacy_infection, "tt_vaccine_efficacy_infection", 1, NA_REAL, NA_REAL, &internal->dim_tt_vaccine_efficacy_infection);
  internal->dim_D_0_1 = internal->N_age;
  internal->dim_D_0_2 = internal->N_vaccine;
  internal->dim_D_1 = internal->N_age;
  internal->dim_D_2 = internal->N_vaccine;
  internal->dim_E_0_1 = internal->N_age;
  internal->dim_E_0_2 = internal->N_vaccine;
  internal->dim_E_1 = internal->N_age;
  internal->dim_E_2 = internal->N_vaccine;
  internal->dim_E_overall = internal->N_age;
  internal->dim_gamma_vaccine = internal->N_vaccine;
  internal->dim_ICase_0_1 = internal->N_age;
  internal->dim_ICase_0_2 = internal->N_vaccine;
  internal->dim_ICase_1 = internal->N_age;
  internal->dim_ICase_2 = internal->N_vaccine;
  internal->dim_ICase_overall = internal->N_age;
  internal->dim_IHosp_0_1 = internal->N_age;
  internal->dim_IHosp_0_2 = internal->N_vaccine;
  internal->dim_IHosp_1 = internal->N_age;
  internal->dim_IHosp_2 = internal->N_vaccine;
  internal->dim_IMild_0_1 = internal->N_age;
  internal->dim_IMild_0_2 = internal->N_vaccine;
  internal->dim_IMild_1 = internal->N_age;
  internal->dim_IMild_2 = internal->N_vaccine;
  internal->dim_IMild_overall = internal->N_age;
  internal->dim_lambda = internal->N_age;
  internal->dim_m_1 = internal->N_age;
  internal->dim_m_2 = internal->N_age;
  internal->dim_N = internal->N_age;
  internal->dim_pop_size = internal->N_age;
  internal->dim_pr = internal->N_age;
  internal->dim_prob_death_hosp_1 = internal->N_age;
  internal->dim_prob_death_hosp_2 = internal->N_vaccine;
  internal->dim_prob_hosp_1 = internal->N_age;
  internal->dim_prob_hosp_2 = internal->N_vaccine;
  internal->dim_R_0_1 = internal->N_age;
  internal->dim_R_0_2 = internal->N_vaccine;
  internal->dim_R_1 = internal->N_age;
  internal->dim_R_2 = internal->N_vaccine;
  internal->dim_R_overall = internal->N_age;
  internal->dim_rel_infectiousness = internal->N_age;
  internal->dim_rel_infectiousness_vaccinated_1 = internal->N_age;
  internal->dim_rel_infectiousness_vaccinated_2 = internal->N_vaccine;
  internal->dim_S_0_1 = internal->N_age;
  internal->dim_S_0_2 = internal->N_vaccine;
  internal->dim_S_1 = internal->N_age;
  internal->dim_S_2 = internal->N_vaccine;
  internal->dim_s_ij_1 = internal->N_age;
  internal->dim_s_ij_2 = internal->N_age;
  internal->dim_S_overall = internal->N_age;
  internal->dim_temp = internal->N_age;
  internal->dim_temp_rel_1 = internal->N_age;
  internal->dim_temp_rel_2 = internal->N_vaccine;
  internal->dim_unvaccinated = internal->N_age;
  internal->dim_vaccinated = internal->N_age;
  internal->dim_vaccination_target = internal->N_age;
  internal->dim_vaccination_target_mat_1 = internal->N_prioritisation_steps;
  internal->dim_vaccination_target_mat_2 = internal->N_age;
  internal->dim_vaccine_coverage_mat_1 = internal->N_prioritisation_steps;
  internal->dim_vaccine_coverage_mat_2 = internal->N_age;
  internal->dim_vaccine_efficacy_infection_t_1 = internal->N_age;
  internal->dim_vaccine_efficacy_infection_t_2 = internal->N_vaccine;
  internal->dim_vaccine_target_vec = internal->N_prioritisation_steps;
  internal->dim_vr_temp = internal->N_age;
  R_Free(internal->lambda);
  internal->lambda = (double*) R_Calloc(internal->dim_lambda, double);
  R_Free(internal->pop_size);
  internal->pop_size = (double*) R_Calloc(internal->dim_pop_size, double);
  R_Free(internal->pr);
  internal->pr = (double*) R_Calloc(internal->dim_pr, double);
  R_Free(internal->temp);
  internal->temp = (double*) R_Calloc(internal->dim_temp, double);
  R_Free(internal->vaccination_target);
  internal->vaccination_target = (double*) R_Calloc(internal->dim_vaccination_target, double);
  R_Free(internal->vaccine_target_vec);
  internal->vaccine_target_vec = (double*) R_Calloc(internal->dim_vaccine_target_vec, double);
  R_Free(internal->vr_temp);
  internal->vr_temp = (double*) R_Calloc(internal->dim_vr_temp, double);
  internal->dim_beta_set = internal->dim_tt_beta;
  internal->dim_D = internal->dim_D_1 * internal->dim_D_2;
  internal->dim_D_0 = internal->dim_D_0_1 * internal->dim_D_0_2;
  internal->dim_E = internal->dim_E_1 * internal->dim_E_2;
  internal->dim_E_0 = internal->dim_E_0_1 * internal->dim_E_0_2;
  internal->dim_ICase = internal->dim_ICase_1 * internal->dim_ICase_2;
  internal->dim_ICase_0 = internal->dim_ICase_0_1 * internal->dim_ICase_0_2;
  internal->dim_IHosp = internal->dim_IHosp_1 * internal->dim_IHosp_2;
  internal->dim_IHosp_0 = internal->dim_IHosp_0_1 * internal->dim_IHosp_0_2;
  internal->dim_IMild = internal->dim_IMild_1 * internal->dim_IMild_2;
  internal->dim_IMild_0 = internal->dim_IMild_0_1 * internal->dim_IMild_0_2;
  internal->dim_m = internal->dim_m_1 * internal->dim_m_2;
  internal->dim_max_vaccine = internal->dim_tt_vaccine;
  internal->dim_mix_mat_set_1 = internal->dim_tt_matrix;
  internal->dim_mix_mat_set_2 = internal->N_age;
  internal->dim_mix_mat_set_3 = internal->N_age;
  internal->dim_prob_death_hosp = internal->dim_prob_death_hosp_1 * internal->dim_prob_death_hosp_2;
  internal->dim_prob_hosp = internal->dim_prob_hosp_1 * internal->dim_prob_hosp_2;
  internal->dim_R = internal->dim_R_1 * internal->dim_R_2;
  internal->dim_R_0 = internal->dim_R_0_1 * internal->dim_R_0_2;
  internal->dim_rel_infectiousness_vaccinated = internal->dim_rel_infectiousness_vaccinated_1 * internal->dim_rel_infectiousness_vaccinated_2;
  internal->dim_S = internal->dim_S_1 * internal->dim_S_2;
  internal->dim_S_0 = internal->dim_S_0_1 * internal->dim_S_0_2;
  internal->dim_s_ij = internal->dim_s_ij_1 * internal->dim_s_ij_2;
  internal->dim_temp_rel = internal->dim_temp_rel_1 * internal->dim_temp_rel_2;
  internal->dim_vaccination_target_mat = internal->dim_vaccination_target_mat_1 * internal->dim_vaccination_target_mat_2;
  internal->dim_vaccine_coverage_mat = internal->dim_vaccine_coverage_mat_1 * internal->dim_vaccine_coverage_mat_2;
  internal->dim_vaccine_efficacy_infection_1 = internal->dim_tt_vaccine_efficacy_infection;
  internal->dim_vaccine_efficacy_infection_2 = internal->N_age;
  internal->dim_vaccine_efficacy_infection_3 = internal->N_vaccine;
  internal->dim_vaccine_efficacy_infection_t = internal->dim_vaccine_efficacy_infection_t_1 * internal->dim_vaccine_efficacy_infection_t_2;
  internal->gamma_vaccine = (double*) user_get_array(user, false, internal->gamma_vaccine, "gamma_vaccine", NA_REAL, NA_REAL, 1, internal->dim_gamma_vaccine);
  internal->offset_output_E_overall = internal->dim_S_overall + 1;
  internal->offset_output_ICase_overall = internal->dim_E_overall + internal->dim_IMild_overall + internal->dim_R_overall + internal->dim_S_overall + 1;
  internal->offset_output_IMild_overall = internal->dim_E_overall + internal->dim_S_overall + 1;
  internal->offset_output_N = internal->dim_E_overall + internal->dim_ICase_overall + internal->dim_IMild_overall + internal->dim_R_overall + internal->dim_S_overall + internal->dim_unvaccinated + internal->dim_vaccinated + 1;
  internal->offset_output_R_overall = internal->dim_E_overall + internal->dim_IMild_overall + internal->dim_S_overall + 1;
  internal->offset_output_unvaccinated = internal->dim_E_overall + internal->dim_ICase_overall + internal->dim_IMild_overall + internal->dim_R_overall + internal->dim_S_overall + 1;
  internal->offset_output_vaccinated = internal->dim_E_overall + internal->dim_ICase_overall + internal->dim_IMild_overall + internal->dim_R_overall + internal->dim_S_overall + internal->dim_unvaccinated + 1;
  internal->rel_infectiousness = (double*) user_get_array(user, false, internal->rel_infectiousness, "rel_infectiousness", NA_REAL, NA_REAL, 1, internal->dim_rel_infectiousness);
  R_Free(internal->initial_D);
  internal->initial_D = (double*) R_Calloc(internal->dim_D, double);
  R_Free(internal->initial_E);
  internal->initial_E = (double*) R_Calloc(internal->dim_E, double);
  R_Free(internal->initial_ICase);
  internal->initial_ICase = (double*) R_Calloc(internal->dim_ICase, double);
  R_Free(internal->initial_IHosp);
  internal->initial_IHosp = (double*) R_Calloc(internal->dim_IHosp, double);
  R_Free(internal->initial_IMild);
  internal->initial_IMild = (double*) R_Calloc(internal->dim_IMild, double);
  R_Free(internal->initial_R);
  internal->initial_R = (double*) R_Calloc(internal->dim_R, double);
  R_Free(internal->initial_S);
  internal->initial_S = (double*) R_Calloc(internal->dim_S, double);
  R_Free(internal->m);
  internal->m = (double*) R_Calloc(internal->dim_m, double);
  R_Free(internal->s_ij);
  internal->s_ij = (double*) R_Calloc(internal->dim_s_ij, double);
  R_Free(internal->temp_rel);
  internal->temp_rel = (double*) R_Calloc(internal->dim_temp_rel, double);
  R_Free(internal->vaccination_target_mat);
  internal->vaccination_target_mat = (double*) R_Calloc(internal->dim_vaccination_target_mat, double);
  R_Free(internal->vaccine_efficacy_infection_t);
  internal->vaccine_efficacy_infection_t = (double*) R_Calloc(internal->dim_vaccine_efficacy_infection_t, double);
  internal->beta_set = (double*) user_get_array(user, false, internal->beta_set, "beta_set", NA_REAL, NA_REAL, 1, internal->dim_beta_set);
  internal->D_0 = (double*) user_get_array(user, false, internal->D_0, "D_0", NA_REAL, NA_REAL, 2, internal->dim_D_0_1, internal->dim_D_0_2);
  internal->dim_mix_mat_set = internal->dim_mix_mat_set_1 * internal->dim_mix_mat_set_2 * internal->dim_mix_mat_set_3;
  internal->dim_mix_mat_set_12 = internal->dim_mix_mat_set_1 * internal->dim_mix_mat_set_2;
  internal->dim_vaccine_efficacy_infection = internal->dim_vaccine_efficacy_infection_1 * internal->dim_vaccine_efficacy_infection_2 * internal->dim_vaccine_efficacy_infection_3;
  internal->dim_vaccine_efficacy_infection_12 = internal->dim_vaccine_efficacy_infection_1 * internal->dim_vaccine_efficacy_infection_2;
  internal->E_0 = (double*) user_get_array(user, false, internal->E_0, "E_0", NA_REAL, NA_REAL, 2, internal->dim_E_0_1, internal->dim_E_0_2);
  internal->ICase_0 = (double*) user_get_array(user, false, internal->ICase_0, "ICase_0", NA_REAL, NA_REAL, 2, internal->dim_ICase_0_1, internal->dim_ICase_0_2);
  internal->IHosp_0 = (double*) user_get_array(user, false, internal->IHosp_0, "IHosp_0", NA_REAL, NA_REAL, 2, internal->dim_IHosp_0_1, internal->dim_IHosp_0_2);
  internal->IMild_0 = (double*) user_get_array(user, false, internal->IMild_0, "IMild_0", NA_REAL, NA_REAL, 2, internal->dim_IMild_0_1, internal->dim_IMild_0_2);
  internal->max_vaccine = (double*) user_get_array(user, false, internal->max_vaccine, "max_vaccine", NA_REAL, NA_REAL, 1, internal->dim_max_vaccine);
  internal->offset_variable_D = internal->dim_E + internal->dim_ICase + internal->dim_IHosp + internal->dim_IMild + internal->dim_R + internal->dim_S;
  internal->offset_variable_ICase = internal->dim_E + internal->dim_IMild + internal->dim_R + internal->dim_S;
  internal->offset_variable_IHosp = internal->dim_E + internal->dim_ICase + internal->dim_IMild + internal->dim_R + internal->dim_S;
  internal->offset_variable_IMild = internal->dim_E + internal->dim_S;
  internal->offset_variable_R = internal->dim_E + internal->dim_IMild + internal->dim_S;
  internal->prob_death_hosp = (double*) user_get_array(user, false, internal->prob_death_hosp, "prob_death_hosp", NA_REAL, NA_REAL, 2, internal->dim_prob_death_hosp_1, internal->dim_prob_death_hosp_2);
  internal->prob_hosp = (double*) user_get_array(user, false, internal->prob_hosp, "prob_hosp", NA_REAL, NA_REAL, 2, internal->dim_prob_hosp_1, internal->dim_prob_hosp_2);
  internal->R_0 = (double*) user_get_array(user, false, internal->R_0, "R_0", NA_REAL, NA_REAL, 2, internal->dim_R_0_1, internal->dim_R_0_2);
  internal->rel_infectiousness_vaccinated = (double*) user_get_array(user, false, internal->rel_infectiousness_vaccinated, "rel_infectiousness_vaccinated", NA_REAL, NA_REAL, 2, internal->dim_rel_infectiousness_vaccinated_1, internal->dim_rel_infectiousness_vaccinated_2);
  internal->S_0 = (double*) user_get_array(user, false, internal->S_0, "S_0", NA_REAL, NA_REAL, 2, internal->dim_S_0_1, internal->dim_S_0_2);
  internal->vaccine_coverage_mat = (double*) user_get_array(user, false, internal->vaccine_coverage_mat, "vaccine_coverage_mat", NA_REAL, NA_REAL, 2, internal->dim_vaccine_coverage_mat_1, internal->dim_vaccine_coverage_mat_2);
  for (int i = 1; i <= internal->dim_D_1; ++i) {
    for (int j = 1; j <= internal->dim_D_2; ++j) {
      internal->initial_D[i - 1 + internal->dim_D_1 * (j - 1)] = internal->D_0[internal->dim_D_0_1 * (j - 1) + i - 1];
    }
  }
  for (int i = 1; i <= internal->dim_E_1; ++i) {
    for (int j = 1; j <= internal->dim_E_2; ++j) {
      internal->initial_E[i - 1 + internal->dim_E_1 * (j - 1)] = internal->E_0[internal->dim_E_0_1 * (j - 1) + i - 1];
    }
  }
  for (int i = 1; i <= internal->dim_ICase_1; ++i) {
    for (int j = 1; j <= internal->dim_ICase_2; ++j) {
      internal->initial_ICase[i - 1 + internal->dim_ICase_1 * (j - 1)] = internal->ICase_0[internal->dim_ICase_0_1 * (j - 1) + i - 1];
    }
  }
  for (int i = 1; i <= internal->dim_IHosp_1; ++i) {
    for (int j = 1; j <= internal->dim_IHosp_2; ++j) {
      internal->initial_IHosp[i - 1 + internal->dim_IHosp_1 * (j - 1)] = internal->IHosp_0[internal->dim_IHosp_0_1 * (j - 1) + i - 1];
    }
  }
  for (int i = 1; i <= internal->dim_IMild_1; ++i) {
    for (int j = 1; j <= internal->dim_IMild_2; ++j) {
      internal->initial_IMild[i - 1 + internal->dim_IMild_1 * (j - 1)] = internal->IMild_0[internal->dim_IMild_0_1 * (j - 1) + i - 1];
    }
  }
  for (int i = 1; i <= internal->dim_R_1; ++i) {
    for (int j = 1; j <= internal->dim_R_2; ++j) {
      internal->initial_R[i - 1 + internal->dim_R_1 * (j - 1)] = internal->R_0[internal->dim_R_0_1 * (j - 1) + i - 1];
    }
  }
  for (int i = 1; i <= internal->dim_S_1; ++i) {
    for (int j = 1; j <= internal->dim_S_2; ++j) {
      internal->initial_S[i - 1 + internal->dim_S_1 * (j - 1)] = internal->S_0[internal->dim_S_0_1 * (j - 1) + i - 1];
    }
  }
  interpolate_check_y(internal->dim_tt_beta, internal->dim_beta_set, 0, "beta_set", "beta");
  cinterpolate_free(internal->interpolate_beta);
  internal->interpolate_beta = cinterpolate_alloc("constant", internal->dim_tt_beta, 1, internal->tt_beta, internal->beta_set, true, false);
  interpolate_check_y(internal->dim_tt_vaccine, internal->dim_max_vaccine, 0, "max_vaccine", "mv");
  cinterpolate_free(internal->interpolate_mv);
  internal->interpolate_mv = cinterpolate_alloc("constant", internal->dim_tt_vaccine, 1, internal->tt_vaccine, internal->max_vaccine, true, false);
  internal->mix_mat_set = (double*) user_get_array(user, false, internal->mix_mat_set, "mix_mat_set", NA_REAL, NA_REAL, 3, internal->dim_mix_mat_set_1, internal->dim_mix_mat_set_2, internal->dim_mix_mat_set_3);
  internal->vaccine_efficacy_infection = (double*) user_get_array(user, false, internal->vaccine_efficacy_infection, "vaccine_efficacy_infection", NA_REAL, NA_REAL, 3, internal->dim_vaccine_efficacy_infection_1, internal->dim_vaccine_efficacy_infection_2, internal->dim_vaccine_efficacy_infection_3);
  interpolate_check_y(internal->dim_tt_matrix, internal->dim_mix_mat_set_1, 1, "mix_mat_set", "m");
  interpolate_check_y(internal->dim_m_1, internal->dim_mix_mat_set_2, 2, "mix_mat_set", "m");
  interpolate_check_y(internal->dim_m_2, internal->dim_mix_mat_set_3, 3, "mix_mat_set", "m");
  cinterpolate_free(internal->interpolate_m);
  internal->interpolate_m = cinterpolate_alloc("constant", internal->dim_tt_matrix, internal->dim_m, internal->tt_matrix, internal->mix_mat_set, true, false);
  interpolate_check_y(internal->dim_tt_vaccine_efficacy_infection, internal->dim_vaccine_efficacy_infection_1, 1, "vaccine_efficacy_infection", "vaccine_efficacy_infection_t");
  interpolate_check_y(internal->dim_vaccine_efficacy_infection_t_1, internal->dim_vaccine_efficacy_infection_2, 2, "vaccine_efficacy_infection", "vaccine_efficacy_infection_t");
  interpolate_check_y(internal->dim_vaccine_efficacy_infection_t_2, internal->dim_vaccine_efficacy_infection_3, 3, "vaccine_efficacy_infection", "vaccine_efficacy_infection_t");
  cinterpolate_free(internal->interpolate_vaccine_efficacy_infection_t);
  internal->interpolate_vaccine_efficacy_infection_t = cinterpolate_alloc("constant", internal->dim_tt_vaccine_efficacy_infection, internal->dim_vaccine_efficacy_infection_t, internal->tt_vaccine_efficacy_infection, internal->vaccine_efficacy_infection, true, false);
  return R_NilValue;
}
SEXP vaccine_simplified_set_initial(SEXP internal_p, SEXP t_ptr, SEXP state_ptr, SEXP vaccine_simplified_use_dde_ptr) {
  return R_NilValue;
}
SEXP vaccine_simplified_metadata(SEXP internal_p) {
  vaccine_simplified_internal *internal = vaccine_simplified_get_internal(internal_p, 1);
  SEXP ret = PROTECT(allocVector(VECSXP, 4));
  SEXP nms = PROTECT(allocVector(STRSXP, 4));
  SET_STRING_ELT(nms, 0, mkChar("variable_order"));
  SET_STRING_ELT(nms, 1, mkChar("output_order"));
  SET_STRING_ELT(nms, 2, mkChar("n_out"));
  SET_STRING_ELT(nms, 3, mkChar("interpolate_t"));
  setAttrib(ret, R_NamesSymbol, nms);
  SEXP variable_length = PROTECT(allocVector(VECSXP, 7));
  SEXP variable_names = PROTECT(allocVector(STRSXP, 7));
  setAttrib(variable_length, R_NamesSymbol, variable_names);
  SET_VECTOR_ELT(variable_length, 0, allocVector(INTSXP, 2));
  int * dim_S = INTEGER(VECTOR_ELT(variable_length, 0));
  dim_S[0] = internal->dim_S_1;
  dim_S[1] = internal->dim_S_2;
  SET_VECTOR_ELT(variable_length, 1, allocVector(INTSXP, 2));
  int * dim_E = INTEGER(VECTOR_ELT(variable_length, 1));
  dim_E[0] = internal->dim_E_1;
  dim_E[1] = internal->dim_E_2;
  SET_VECTOR_ELT(variable_length, 2, allocVector(INTSXP, 2));
  int * dim_IMild = INTEGER(VECTOR_ELT(variable_length, 2));
  dim_IMild[0] = internal->dim_IMild_1;
  dim_IMild[1] = internal->dim_IMild_2;
  SET_VECTOR_ELT(variable_length, 3, allocVector(INTSXP, 2));
  int * dim_R = INTEGER(VECTOR_ELT(variable_length, 3));
  dim_R[0] = internal->dim_R_1;
  dim_R[1] = internal->dim_R_2;
  SET_VECTOR_ELT(variable_length, 4, allocVector(INTSXP, 2));
  int * dim_ICase = INTEGER(VECTOR_ELT(variable_length, 4));
  dim_ICase[0] = internal->dim_ICase_1;
  dim_ICase[1] = internal->dim_ICase_2;
  SET_VECTOR_ELT(variable_length, 5, allocVector(INTSXP, 2));
  int * dim_IHosp = INTEGER(VECTOR_ELT(variable_length, 5));
  dim_IHosp[0] = internal->dim_IHosp_1;
  dim_IHosp[1] = internal->dim_IHosp_2;
  SET_VECTOR_ELT(variable_length, 6, allocVector(INTSXP, 2));
  int * dim_D = INTEGER(VECTOR_ELT(variable_length, 6));
  dim_D[0] = internal->dim_D_1;
  dim_D[1] = internal->dim_D_2;
  SET_STRING_ELT(variable_names, 0, mkChar("S"));
  SET_STRING_ELT(variable_names, 1, mkChar("E"));
  SET_STRING_ELT(variable_names, 2, mkChar("IMild"));
  SET_STRING_ELT(variable_names, 3, mkChar("R"));
  SET_STRING_ELT(variable_names, 4, mkChar("ICase"));
  SET_STRING_ELT(variable_names, 5, mkChar("IHosp"));
  SET_STRING_ELT(variable_names, 6, mkChar("D"));
  SET_VECTOR_ELT(ret, 0, variable_length);
  UNPROTECT(2);
  SEXP output_length = PROTECT(allocVector(VECSXP, 9));
  SEXP output_names = PROTECT(allocVector(STRSXP, 9));
  setAttrib(output_length, R_NamesSymbol, output_names);
  SET_VECTOR_ELT(output_length, 0, R_NilValue);
  SET_VECTOR_ELT(output_length, 1, ScalarInteger(internal->dim_S_overall));
  SET_VECTOR_ELT(output_length, 2, ScalarInteger(internal->dim_E_overall));
  SET_VECTOR_ELT(output_length, 3, ScalarInteger(internal->dim_IMild_overall));
  SET_VECTOR_ELT(output_length, 4, ScalarInteger(internal->dim_R_overall));
  SET_VECTOR_ELT(output_length, 5, ScalarInteger(internal->dim_ICase_overall));
  SET_VECTOR_ELT(output_length, 6, ScalarInteger(internal->dim_unvaccinated));
  SET_VECTOR_ELT(output_length, 7, ScalarInteger(internal->dim_vaccinated));
  SET_VECTOR_ELT(output_length, 8, ScalarInteger(internal->dim_N));
  SET_STRING_ELT(output_names, 0, mkChar("time"));
  SET_STRING_ELT(output_names, 1, mkChar("S_overall"));
  SET_STRING_ELT(output_names, 2, mkChar("E_overall"));
  SET_STRING_ELT(output_names, 3, mkChar("IMild_overall"));
  SET_STRING_ELT(output_names, 4, mkChar("R_overall"));
  SET_STRING_ELT(output_names, 5, mkChar("ICase_overall"));
  SET_STRING_ELT(output_names, 6, mkChar("unvaccinated"));
  SET_STRING_ELT(output_names, 7, mkChar("vaccinated"));
  SET_STRING_ELT(output_names, 8, mkChar("N"));
  SET_VECTOR_ELT(ret, 1, output_length);
  UNPROTECT(2);
  SET_VECTOR_ELT(ret, 2, ScalarInteger(internal->dim_E_overall + internal->dim_ICase_overall + internal->dim_IMild_overall + internal->dim_N + internal->dim_R_overall + internal->dim_S_overall + internal->dim_unvaccinated + internal->dim_vaccinated + 1));
  SEXP interpolate_t = PROTECT(allocVector(VECSXP, 3));
  SEXP interpolate_t_nms = PROTECT(allocVector(STRSXP, 3));
  setAttrib(interpolate_t, R_NamesSymbol, interpolate_t_nms);
  SET_VECTOR_ELT(interpolate_t, 0, ScalarReal(fmax(internal->tt_beta[0], fmax(internal->tt_matrix[0], fmax(internal->tt_vaccine[0], internal->tt_vaccine_efficacy_infection[0])))));
  SET_VECTOR_ELT(interpolate_t, 1, ScalarReal(R_PosInf));
  SET_STRING_ELT(interpolate_t_nms, 0, mkChar("min"));
  SET_STRING_ELT(interpolate_t_nms, 1, mkChar("max"));
  SET_VECTOR_ELT(ret, 3, interpolate_t);
  UNPROTECT(2);
  UNPROTECT(2);
  return ret;
}
SEXP vaccine_simplified_initial_conditions(SEXP internal_p, SEXP t_ptr) {
  vaccine_simplified_internal *internal = vaccine_simplified_get_internal(internal_p, 1);
  SEXP r_state = PROTECT(allocVector(REALSXP, internal->dim_D + internal->dim_E + internal->dim_ICase + internal->dim_IHosp + internal->dim_IMild + internal->dim_R + internal->dim_S));
  double * state = REAL(r_state);
  memcpy(state + 0, internal->initial_S, internal->dim_S * sizeof(double));
  memcpy(state + internal->dim_S, internal->initial_E, internal->dim_E * sizeof(double));
  memcpy(state + internal->offset_variable_IMild, internal->initial_IMild, internal->dim_IMild * sizeof(double));
  memcpy(state + internal->offset_variable_R, internal->initial_R, internal->dim_R * sizeof(double));
  memcpy(state + internal->offset_variable_ICase, internal->initial_ICase, internal->dim_ICase * sizeof(double));
  memcpy(state + internal->offset_variable_IHosp, internal->initial_IHosp, internal->dim_IHosp * sizeof(double));
  memcpy(state + internal->offset_variable_D, internal->initial_D, internal->dim_D * sizeof(double));
  UNPROTECT(1);
  return r_state;
}
void vaccine_simplified_rhs(vaccine_simplified_internal* internal, double t, double * state, double * dstatedt, double * output) {
  double * S = state + 0;
  double * E = state + internal->dim_S;
  double * IMild = state + internal->offset_variable_IMild;
  double * R = state + internal->offset_variable_R;
  double * ICase = state + internal->offset_variable_ICase;
  double * IHosp = state + internal->offset_variable_IHosp;
  double * D = state + internal->offset_variable_D;
  for (int i = 1; i <= internal->dim_IHosp_1; ++i) {
    int j = 1;
    dstatedt[internal->offset_variable_IHosp + i - 1 + internal->dim_IHosp_1 * (j - 1)] = (internal->gamma_ICase * ICase[internal->dim_ICase_1 * (j - 1) + i - 1]) - (internal->gamma_IHosp * IHosp[internal->dim_IHosp_1 * (j - 1) + i - 1]);
  }
  for (int i = 1; i <= internal->dim_IHosp_1; ++i) {
    int j = 2;
    dstatedt[internal->offset_variable_IHosp + i - 1 + internal->dim_IHosp_1 * (j - 1)] = (internal->gamma_ICase * ICase[internal->dim_ICase_1 * (j - 1) + i - 1]) - (internal->gamma_IHosp * IHosp[internal->dim_IHosp_1 * (j - 1) + i - 1]) - (internal->gamma_vaccine[j - 1] * IHosp[internal->dim_IHosp_1 * (j - 1) + i - 1]);
  }
  for (int i = 1; i <= internal->dim_IHosp_1; ++i) {
    for (int j = 3; j <= internal->N_vaccine; ++j) {
      dstatedt[internal->offset_variable_IHosp + i - 1 + internal->dim_IHosp_1 * (j - 1)] = (internal->gamma_vaccine[j - 1 - 1] * IHosp[internal->dim_IHosp_1 * (j - 1 - 1) + i - 1]) + (internal->gamma_ICase * ICase[internal->dim_ICase_1 * (j - 1) + i - 1]) - (internal->gamma_IHosp * IHosp[internal->dim_IHosp_1 * (j - 1) + i - 1]) - (internal->gamma_vaccine[j - 1] * IHosp[internal->dim_IHosp_1 * (j - 1) + i - 1]);
    }
  }
  for (int i = 1; i <= internal->dim_pop_size; ++i) {
    internal->pop_size[i - 1] = odin_sum2(S, i - 1, i, 0, internal->dim_S_2, internal->dim_S_1) + odin_sum2(E, i - 1, i, 0, internal->dim_E_2, internal->dim_E_1) + odin_sum2(IMild, i - 1, i, 0, internal->dim_IMild_2, internal->dim_IMild_1) + odin_sum2(ICase, i - 1, i, 0, internal->dim_ICase_2, internal->dim_ICase_1) + odin_sum2(IHosp, i - 1, i, 0, internal->dim_IHosp_2, internal->dim_IHosp_1) + odin_sum2(R, i - 1, i, 0, internal->dim_R_2, internal->dim_R_1);
  }
  for (int i = 1; i <= internal->dim_D_1; ++i) {
    int j = 1;
    dstatedt[internal->offset_variable_D + i - 1 + internal->dim_D_1 * (j - 1)] = (internal->gamma_IHosp * IHosp[internal->dim_IHosp_1 * (j - 1) + i - 1] * internal->prob_death_hosp[internal->dim_prob_death_hosp_1 * (j - 1) + i - 1]);
  }
  for (int i = 1; i <= internal->dim_D_1; ++i) {
    int j = 2;
    dstatedt[internal->offset_variable_D + i - 1 + internal->dim_D_1 * (j - 1)] = (internal->gamma_IHosp * IHosp[internal->dim_IHosp_1 * (j - 1) + i - 1] * internal->prob_death_hosp[internal->dim_prob_death_hosp_1 * (j - 1) + i - 1]) - (internal->gamma_vaccine[j - 1] * D[internal->dim_D_1 * (j - 1) + i - 1]);
  }
  for (int i = 1; i <= internal->dim_D_1; ++i) {
    for (int j = 3; j <= internal->N_vaccine; ++j) {
      dstatedt[internal->offset_variable_D + i - 1 + internal->dim_D_1 * (j - 1)] = (internal->gamma_vaccine[j - 1 - 1] * D[internal->dim_D_1 * (j - 1 - 1) + i - 1]) + (internal->gamma_IHosp * IHosp[internal->dim_IHosp_1 * (j - 1) + i - 1] * internal->prob_death_hosp[internal->dim_prob_death_hosp_1 * (j - 1) + i - 1]) - (internal->gamma_vaccine[j - 1] * D[internal->dim_D_1 * (j - 1) + i - 1]);
    }
  }
  for (int i = 1; i <= internal->dim_ICase_1; ++i) {
    int j = 1;
    dstatedt[internal->offset_variable_ICase + i - 1 + internal->dim_ICase_1 * (j - 1)] = (internal->gamma_E * E[internal->dim_E_1 * (j - 1) + i - 1] * internal->prob_hosp[internal->dim_prob_hosp_1 * (j - 1) + i - 1]) - (internal->gamma_ICase * ICase[internal->dim_ICase_1 * (j - 1) + i - 1]);
  }
  for (int i = 1; i <= internal->dim_ICase_1; ++i) {
    int j = 2;
    dstatedt[internal->offset_variable_ICase + i - 1 + internal->dim_ICase_1 * (j - 1)] = (internal->gamma_E * E[internal->dim_E_1 * (j - 1) + i - 1] * internal->prob_hosp[internal->dim_prob_hosp_1 * (j - 1) + i - 1]) - (internal->gamma_ICase * ICase[internal->dim_ICase_1 * (j - 1) + i - 1]) - (internal->gamma_vaccine[j - 1] * ICase[internal->dim_ICase_1 * (j - 1) + i - 1]);
  }
  for (int i = 1; i <= internal->dim_ICase_1; ++i) {
    for (int j = 3; j <= internal->N_vaccine; ++j) {
      dstatedt[internal->offset_variable_ICase + i - 1 + internal->dim_ICase_1 * (j - 1)] = (internal->gamma_vaccine[j - 1 - 1] * ICase[internal->dim_ICase_1 * (j - 1 - 1) + i - 1]) + (internal->gamma_E * E[internal->dim_E_1 * (j - 1) + i - 1] * internal->prob_hosp[internal->dim_prob_hosp_1 * (j - 1) + i - 1]) - (internal->gamma_ICase * ICase[internal->dim_ICase_1 * (j - 1) + i - 1]) - (internal->gamma_vaccine[j - 1] * ICase[internal->dim_ICase_1 * (j - 1) + i - 1]);
    }
  }
  for (int i = 1; i <= internal->dim_IMild_1; ++i) {
    int j = 1;
    dstatedt[internal->offset_variable_IMild + i - 1 + internal->dim_IMild_1 * (j - 1)] = (internal->gamma_E * E[internal->dim_E_1 * (j - 1) + i - 1] * (1 - internal->prob_hosp[internal->dim_prob_hosp_1 * (j - 1) + i - 1])) - (internal->gamma_IMild * IMild[internal->dim_IMild_1 * (j - 1) + i - 1]);
  }
  for (int i = 1; i <= internal->dim_IMild_1; ++i) {
    int j = 2;
    dstatedt[internal->offset_variable_IMild + i - 1 + internal->dim_IMild_1 * (j - 1)] = (internal->gamma_E * E[internal->dim_E_1 * (j - 1) + i - 1] * (1 - internal->prob_hosp[internal->dim_prob_hosp_1 * (j - 1) + i - 1])) - (internal->gamma_IMild * IMild[internal->dim_IMild_1 * (j - 1) + i - 1]) - (internal->gamma_vaccine[j - 1] * IMild[internal->dim_IMild_1 * (j - 1) + i - 1]);
  }
  for (int i = 1; i <= internal->dim_IMild_1; ++i) {
    for (int j = 3; j <= internal->N_vaccine; ++j) {
      dstatedt[internal->offset_variable_IMild + i - 1 + internal->dim_IMild_1 * (j - 1)] = (internal->gamma_vaccine[j - 1 - 1] * IMild[internal->dim_IMild_1 * (j - 1 - 1) + i - 1]) + (internal->gamma_E * E[internal->dim_E_1 * (j - 1) + i - 1] * (1 - internal->prob_hosp[internal->dim_prob_hosp_1 * (j - 1) + i - 1])) - (internal->gamma_IMild * IMild[internal->dim_IMild_1 * (j - 1) + i - 1]) - (internal->gamma_vaccine[j - 1] * IMild[internal->dim_IMild_1 * (j - 1) + i - 1]);
    }
  }
  for (int i = 1; i <= internal->dim_pr; ++i) {
    internal->pr[i - 1] = 1 - ((odin_sum2(S, i - 1, i, 0, 1, internal->dim_S_1) + odin_sum2(E, i - 1, i, 0, 1, internal->dim_E_1) + odin_sum2(IMild, i - 1, i, 0, 1, internal->dim_IMild_1) + odin_sum2(ICase, i - 1, i, 0, 1, internal->dim_ICase_1) + odin_sum2(IHosp, i - 1, i, 0, 1, internal->dim_IHosp_1) + odin_sum2(R, i - 1, i, 0, 1, internal->dim_R_1)) / (double) (internal->pop_size[i - 1]));
  }
  for (int i = 1; i <= internal->dim_temp_rel_1; ++i) {
    for (int j = 1; j <= internal->dim_temp_rel_2; ++j) {
      internal->temp_rel[i - 1 + internal->dim_temp_rel_1 * (j - 1)] = (IMild[internal->dim_IMild_1 * (j - 1) + i - 1] * internal->rel_infectiousness_vaccinated[internal->dim_rel_infectiousness_vaccinated_1 * (j - 1) + i - 1]) + (ICase[internal->dim_ICase_1 * (j - 1) + i - 1] * internal->rel_infectiousness_vaccinated[internal->dim_rel_infectiousness_vaccinated_1 * (j - 1) + i - 1]);
    }
  }
  double beta = 0.0;
  cinterpolate_eval(t, internal->interpolate_beta, &beta);
  double mv = 0.0;
  cinterpolate_eval(t, internal->interpolate_mv, &mv);
  for (int i = 1; i <= internal->dim_temp; ++i) {
    internal->temp[i - 1] = odin_sum2(internal->temp_rel, i - 1, i, 0, internal->dim_temp_rel_2, internal->dim_temp_rel_1);
  }
  for (int i = 1; i <= internal->dim_vaccination_target_mat_1; ++i) {
    for (int j = 1; j <= internal->dim_vaccination_target_mat_2; ++j) {
      internal->vaccination_target_mat[i - 1 + internal->dim_vaccination_target_mat_1 * (j - 1)] = (internal->pr[j - 1] < internal->vaccine_coverage_mat[internal->dim_vaccine_coverage_mat_1 * (j - 1) + i - 1] ? 1 : 0);
    }
  }
  cinterpolate_eval(t, internal->interpolate_m, internal->m);
  cinterpolate_eval(t, internal->interpolate_vaccine_efficacy_infection_t, internal->vaccine_efficacy_infection_t);
  for (int i = 1; i <= internal->dim_vaccine_target_vec; ++i) {
    internal->vaccine_target_vec[i - 1] = (odin_sum2(internal->vaccination_target_mat, i - 1, i, 0, internal->dim_vaccination_target_mat_2, internal->dim_vaccination_target_mat_1) == 0 ? 1 : 0);
  }
  double current_index = fmin(odin_sum1(internal->vaccine_target_vec, 0, internal->dim_vaccine_target_vec) + 1, internal->N_prioritisation_steps);
  for (int i = 1; i <= internal->dim_s_ij_1; ++i) {
    for (int j = 1; j <= internal->dim_s_ij_2; ++j) {
      internal->s_ij[i - 1 + internal->dim_s_ij_1 * (j - 1)] = internal->m[internal->dim_m_1 * (j - 1) + i - 1] * internal->temp[j - 1] * internal->rel_infectiousness[j - 1];
    }
  }
  for (int i = 1; i <= internal->dim_lambda; ++i) {
    internal->lambda[i - 1] = beta * odin_sum2(internal->s_ij, i - 1, i, 0, internal->dim_s_ij_2, internal->dim_s_ij_1);
  }
  for (int i = 1; i <= internal->dim_vaccination_target; ++i) {
    internal->vaccination_target[i - 1] = internal->vaccination_target_mat[internal->dim_vaccination_target_mat_1 * (i - 1) + (int) (current_index) - 1];
  }
  for (int i = 1; i <= internal->dim_vr_temp; ++i) {
    internal->vr_temp[i - 1] = S[internal->dim_S_1 * 0 + i - 1] * internal->vaccination_target[i - 1] + E[internal->dim_E_1 * 0 + i - 1] * internal->vaccination_target[i - 1] + +(R[internal->dim_R_1 * 0 + i - 1]) * internal->vaccination_target[i - 1];
  }
  double vr_den = (odin_sum1(internal->vr_temp, 0, internal->dim_vr_temp) <= mv ? mv : odin_sum1(internal->vr_temp, 0, internal->dim_vr_temp));
  double vr = (mv == 0 ? 0 : mv / (double) vr_den);
  for (int i = 1; i <= internal->dim_E_1; ++i) {
    int j = 1;
    dstatedt[internal->dim_S + i - 1 + internal->dim_E_1 * (j - 1)] = (internal->lambda[i - 1] * internal->vaccine_efficacy_infection_t[internal->dim_vaccine_efficacy_infection_t_1 * (j - 1) + i - 1] * S[internal->dim_S_1 * (j - 1) + i - 1]) - (internal->gamma_E * E[internal->dim_E_1 * (j - 1) + i - 1]) - (vr * internal->vaccination_target[i - 1] * E[internal->dim_E_1 * (j - 1) + i - 1]);
  }
  for (int i = 1; i <= internal->dim_E_1; ++i) {
    int j = 2;
    dstatedt[internal->dim_S + i - 1 + internal->dim_E_1 * (j - 1)] = (internal->lambda[i - 1] * internal->vaccine_efficacy_infection_t[internal->dim_vaccine_efficacy_infection_t_1 * (j - 1) + i - 1] * S[internal->dim_S_1 * (j - 1) + i - 1]) - (internal->gamma_E * E[internal->dim_E_1 * (j - 1) + i - 1]) + (vr * internal->vaccination_target[i - 1] * E[internal->dim_E_1 * (j - 1 - 1) + i - 1]) - (internal->gamma_vaccine[j - 1] * E[internal->dim_E_1 * (j - 1) + i - 1]);
  }
  for (int i = 1; i <= internal->dim_E_1; ++i) {
    for (int j = 3; j <= internal->N_vaccine; ++j) {
      dstatedt[internal->dim_S + i - 1 + internal->dim_E_1 * (j - 1)] = (internal->gamma_vaccine[j - 1 - 1] * E[internal->dim_E_1 * (j - 1 - 1) + i - 1]) + (internal->lambda[i - 1] * internal->vaccine_efficacy_infection_t[internal->dim_vaccine_efficacy_infection_t_1 * (j - 1) + i - 1] * S[internal->dim_S_1 * (j - 1) + i - 1]) - (internal->gamma_E * E[internal->dim_E_1 * (j - 1) + i - 1]) - (internal->gamma_vaccine[j - 1] * E[internal->dim_E_1 * (j - 1) + i - 1]);
    }
  }
  for (int i = 1; i <= internal->dim_R_1; ++i) {
    int j = 1;
    dstatedt[internal->offset_variable_R + i - 1 + internal->dim_R_1 * (j - 1)] = (internal->gamma_IHosp * IHosp[internal->dim_IHosp_1 * (j - 1) + i - 1] * (1 - internal->prob_death_hosp[internal->dim_prob_death_hosp_1 * (j - 1) + i - 1])) + (internal->gamma_IMild * IMild[internal->dim_IMild_1 * (j - 1) + i - 1]) - (vr * internal->vaccination_target[i - 1] * R[internal->dim_R_1 * (j - 1) + i - 1]);
  }
  for (int i = 1; i <= internal->dim_R_1; ++i) {
    int j = 2;
    dstatedt[internal->offset_variable_R + i - 1 + internal->dim_R_1 * (j - 1)] = (vr * internal->vaccination_target[i - 1] * R[internal->dim_R_1 * (j - 1 - 1) + i - 1]) + (internal->gamma_IHosp * IHosp[internal->dim_IHosp_1 * (j - 1) + i - 1] * (1 - internal->prob_death_hosp[internal->dim_prob_death_hosp_1 * (j - 1) + i - 1])) + (internal->gamma_IMild * IMild[internal->dim_IMild_1 * (j - 1) + i - 1]) - (internal->gamma_vaccine[j - 1] * R[internal->dim_R_1 * (j - 1) + i - 1]);
  }
  for (int i = 1; i <= internal->dim_R_1; ++i) {
    for (int j = 3; j <= internal->N_vaccine; ++j) {
      dstatedt[internal->offset_variable_R + i - 1 + internal->dim_R_1 * (j - 1)] = (internal->gamma_vaccine[j - 1 - 1] * R[internal->dim_R_1 * (j - 1 - 1) + i - 1]) + (internal->gamma_IHosp * IHosp[internal->dim_IHosp_1 * (j - 1) + i - 1] * (1 - internal->prob_death_hosp[internal->dim_prob_death_hosp_1 * (j - 1) + i - 1])) + (internal->gamma_IMild * IMild[internal->dim_IMild_1 * (j - 1) + i - 1]) - (internal->gamma_vaccine[j - 1] * R[internal->dim_R_1 * (j - 1) + i - 1]);
    }
  }
  for (int i = 1; i <= internal->dim_S_1; ++i) {
    int j = 1;
    dstatedt[0 + i - 1 + internal->dim_S_1 * (j - 1)] = -((internal->lambda[i - 1] * internal->vaccine_efficacy_infection_t[internal->dim_vaccine_efficacy_infection_t_1 * (j - 1) + i - 1] * S[internal->dim_S_1 * (j - 1) + i - 1])) - (vr * internal->vaccination_target[i - 1] * S[internal->dim_S_1 * (j - 1) + i - 1]);
  }
  for (int i = 1; i <= internal->dim_S_1; ++i) {
    int j = 2;
    dstatedt[0 + i - 1 + internal->dim_S_1 * (j - 1)] = -((internal->lambda[i - 1] * internal->vaccine_efficacy_infection_t[internal->dim_vaccine_efficacy_infection_t_1 * (j - 1) + i - 1] * S[internal->dim_S_1 * (j - 1) + i - 1])) + (vr * internal->vaccination_target[i - 1] * S[internal->dim_S_1 * (j - 1 - 1) + i - 1]) - (internal->gamma_vaccine[j - 1] * S[internal->dim_S_1 * (j - 1) + i - 1]);
  }
  for (int i = 1; i <= internal->dim_S_1; ++i) {
    for (int j = 3; j <= internal->N_vaccine; ++j) {
      dstatedt[0 + i - 1 + internal->dim_S_1 * (j - 1)] = (internal->gamma_vaccine[j - 1 - 1] * S[internal->dim_S_1 * (j - 1 - 1) + i - 1]) - (internal->lambda[i - 1] * internal->vaccine_efficacy_infection_t[internal->dim_vaccine_efficacy_infection_t_1 * (j - 1) + i - 1] * S[internal->dim_S_1 * (j - 1) + i - 1]) - (internal->gamma_vaccine[j - 1] * S[internal->dim_S_1 * (j - 1) + i - 1]);
    }
  }
  if (output) {
    double time = t;
    output[0] = time;
    for (int i = 1; i <= internal->dim_unvaccinated; ++i) {
      output[internal->offset_output_unvaccinated + i - 1] = odin_sum2(S, i - 1, i, 0, 1, internal->dim_S_1) + odin_sum2(E, i - 1, i, 0, 1, internal->dim_E_1) + odin_sum2(IMild, i - 1, i, 0, 1, internal->dim_IMild_1) + odin_sum2(ICase, i - 1, i, 0, 1, internal->dim_ICase_1) + odin_sum2(IHosp, i - 1, i, 0, 1, internal->dim_IHosp_1) + odin_sum2(R, i - 1, i, 0, 1, internal->dim_R_1) + odin_sum2(D, i - 1, i, 0, 1, internal->dim_D_1);
    }
    for (int i = 1; i <= internal->dim_vaccinated; ++i) {
      output[internal->offset_output_vaccinated + i - 1] = odin_sum2(S, i - 1, i, 1, internal->N_vaccine, internal->dim_S_1) + odin_sum2(E, i - 1, i, 1, internal->N_vaccine, internal->dim_E_1) + odin_sum2(IMild, i - 1, i, 1, internal->N_vaccine, internal->dim_IMild_1) + odin_sum2(ICase, i - 1, i, 1, internal->N_vaccine, internal->dim_ICase_1) + odin_sum2(IHosp, i - 1, i, 1, internal->N_vaccine, internal->dim_IHosp_1) + odin_sum2(R, i - 1, i, 1, internal->N_vaccine, internal->dim_R_1) + odin_sum2(D, i - 1, i, 1, internal->N_vaccine, internal->dim_D_1);
    }
    for (int i = 1; i <= internal->dim_E_overall; ++i) {
      output[internal->offset_output_E_overall + i - 1] = odin_sum2(E, i - 1, i, 0, internal->dim_E_2, internal->dim_E_1);
    }
    for (int i = 1; i <= internal->dim_ICase_overall; ++i) {
      output[internal->offset_output_ICase_overall + i - 1] = odin_sum2(ICase, i - 1, i, 0, internal->dim_ICase_2, internal->dim_ICase_1);
    }
    for (int i = 1; i <= internal->dim_IMild_overall; ++i) {
      output[internal->offset_output_IMild_overall + i - 1] = odin_sum2(IMild, i - 1, i, 0, internal->dim_IMild_2, internal->dim_IMild_1);
    }
    for (int i = 1; i <= internal->dim_R_overall; ++i) {
      output[internal->offset_output_R_overall + i - 1] = odin_sum2(R, i - 1, i, 0, internal->dim_R_2, internal->dim_R_1);
    }
    for (int i = 1; i <= internal->dim_S_overall; ++i) {
      output[1 + i - 1] = odin_sum2(S, i - 1, i, 0, internal->dim_S_2, internal->dim_S_1);
    }
    for (int i = 1; i <= internal->dim_N; ++i) {
      output[internal->offset_output_N + i - 1] = internal->pop_size[i - 1] + odin_sum2(D, i - 1, i, 0, internal->dim_D_2, internal->dim_D_1);
    }
  }
}
void vaccine_simplified_rhs_dde(size_t neq, double t, double * state, double * dstatedt, void * internal) {
  vaccine_simplified_rhs((vaccine_simplified_internal*)internal, t, state, dstatedt, NULL);
}
void vaccine_simplified_rhs_desolve(int * neq, double * t, double * state, double * dstatedt, double * output, int * np) {
  vaccine_simplified_rhs(vaccine_simplified_internal_ds, *t, state, dstatedt, output);
}
void vaccine_simplified_output_dde(size_t n_eq, double t, double * state, size_t n_output, double * output, void * internal_p) {
  vaccine_simplified_internal *internal = (vaccine_simplified_internal*) internal_p;
  double * S = state + 0;
  double * E = state + internal->dim_S;
  double * IMild = state + internal->offset_variable_IMild;
  double * R = state + internal->offset_variable_R;
  double * ICase = state + internal->offset_variable_ICase;
  double * IHosp = state + internal->offset_variable_IHosp;
  double * D = state + internal->offset_variable_D;
  double time = t;
  output[0] = time;
  for (int i = 1; i <= internal->dim_unvaccinated; ++i) {
    output[internal->offset_output_unvaccinated + i - 1] = odin_sum2(S, i - 1, i, 0, 1, internal->dim_S_1) + odin_sum2(E, i - 1, i, 0, 1, internal->dim_E_1) + odin_sum2(IMild, i - 1, i, 0, 1, internal->dim_IMild_1) + odin_sum2(ICase, i - 1, i, 0, 1, internal->dim_ICase_1) + odin_sum2(IHosp, i - 1, i, 0, 1, internal->dim_IHosp_1) + odin_sum2(R, i - 1, i, 0, 1, internal->dim_R_1) + odin_sum2(D, i - 1, i, 0, 1, internal->dim_D_1);
  }
  for (int i = 1; i <= internal->dim_vaccinated; ++i) {
    output[internal->offset_output_vaccinated + i - 1] = odin_sum2(S, i - 1, i, 1, internal->N_vaccine, internal->dim_S_1) + odin_sum2(E, i - 1, i, 1, internal->N_vaccine, internal->dim_E_1) + odin_sum2(IMild, i - 1, i, 1, internal->N_vaccine, internal->dim_IMild_1) + odin_sum2(ICase, i - 1, i, 1, internal->N_vaccine, internal->dim_ICase_1) + odin_sum2(IHosp, i - 1, i, 1, internal->N_vaccine, internal->dim_IHosp_1) + odin_sum2(R, i - 1, i, 1, internal->N_vaccine, internal->dim_R_1) + odin_sum2(D, i - 1, i, 1, internal->N_vaccine, internal->dim_D_1);
  }
  for (int i = 1; i <= internal->dim_E_overall; ++i) {
    output[internal->offset_output_E_overall + i - 1] = odin_sum2(E, i - 1, i, 0, internal->dim_E_2, internal->dim_E_1);
  }
  for (int i = 1; i <= internal->dim_ICase_overall; ++i) {
    output[internal->offset_output_ICase_overall + i - 1] = odin_sum2(ICase, i - 1, i, 0, internal->dim_ICase_2, internal->dim_ICase_1);
  }
  for (int i = 1; i <= internal->dim_IMild_overall; ++i) {
    output[internal->offset_output_IMild_overall + i - 1] = odin_sum2(IMild, i - 1, i, 0, internal->dim_IMild_2, internal->dim_IMild_1);
  }
  for (int i = 1; i <= internal->dim_R_overall; ++i) {
    output[internal->offset_output_R_overall + i - 1] = odin_sum2(R, i - 1, i, 0, internal->dim_R_2, internal->dim_R_1);
  }
  for (int i = 1; i <= internal->dim_S_overall; ++i) {
    output[1 + i - 1] = odin_sum2(S, i - 1, i, 0, internal->dim_S_2, internal->dim_S_1);
  }
  for (int i = 1; i <= internal->dim_pop_size; ++i) {
    internal->pop_size[i - 1] = odin_sum2(S, i - 1, i, 0, internal->dim_S_2, internal->dim_S_1) + odin_sum2(E, i - 1, i, 0, internal->dim_E_2, internal->dim_E_1) + odin_sum2(IMild, i - 1, i, 0, internal->dim_IMild_2, internal->dim_IMild_1) + odin_sum2(ICase, i - 1, i, 0, internal->dim_ICase_2, internal->dim_ICase_1) + odin_sum2(IHosp, i - 1, i, 0, internal->dim_IHosp_2, internal->dim_IHosp_1) + odin_sum2(R, i - 1, i, 0, internal->dim_R_2, internal->dim_R_1);
  }
  for (int i = 1; i <= internal->dim_N; ++i) {
    output[internal->offset_output_N + i - 1] = internal->pop_size[i - 1] + odin_sum2(D, i - 1, i, 0, internal->dim_D_2, internal->dim_D_1);
  }
}
SEXP vaccine_simplified_rhs_r(SEXP internal_p, SEXP t, SEXP state) {
  SEXP dstatedt = PROTECT(allocVector(REALSXP, LENGTH(state)));
  vaccine_simplified_internal *internal = vaccine_simplified_get_internal(internal_p, 1);
  SEXP output_ptr = PROTECT(allocVector(REALSXP, internal->dim_E_overall + internal->dim_ICase_overall + internal->dim_IMild_overall + internal->dim_N + internal->dim_R_overall + internal->dim_S_overall + internal->dim_unvaccinated + internal->dim_vaccinated + 1));
  setAttrib(dstatedt, install("output"), output_ptr);
  UNPROTECT(1);
  double *output = REAL(output_ptr);
  vaccine_simplified_rhs(internal, scalar_real(t, "t"), REAL(state), REAL(dstatedt), output);
  UNPROTECT(1);
  return dstatedt;
}
double user_get_scalar_double(SEXP user, const char *name,
                              double default_value, double min, double max) {
  double ret = default_value;
  SEXP el = user_list_element(user, name);
  if (el != R_NilValue) {
    if (length(el) != 1) {
      Rf_error("Expected a scalar numeric for '%s'", name);
    }
    if (TYPEOF(el) == REALSXP) {
      ret = REAL(el)[0];
    } else if (TYPEOF(el) == INTSXP) {
      ret = INTEGER(el)[0];
    } else {
      Rf_error("Expected a numeric value for '%s'", name);
    }
  }
  if (ISNA(ret)) {
    Rf_error("Expected a value for '%s'", name);
  }
  user_check_values_double(&ret, 1, min, max, name);
  return ret;
}
int user_get_scalar_int(SEXP user, const char *name,
                        int default_value, double min, double max) {
  int ret = default_value;
  SEXP el = user_list_element(user, name);
  if (el != R_NilValue) {
    if (length(el) != 1) {
      Rf_error("Expected scalar integer for '%s'", name);
    }
    if (TYPEOF(el) == REALSXP) {
      double tmp = REAL(el)[0];
      if (fabs(tmp - round(tmp)) > 2e-8) {
        Rf_error("Expected '%s' to be integer-like", name);
      }
    }
    ret = INTEGER(coerceVector(el, INTSXP))[0];
  }
  if (ret == NA_INTEGER) {
    Rf_error("Expected a value for '%s'", name);
  }
  user_check_values_int(&ret, 1, min, max, name);
  return ret;
}
void user_check_values_double(double * value, size_t len,
                                  double min, double max, const char *name) {
  for (size_t i = 0; i < len; ++i) {
    if (ISNA(value[i])) {
      Rf_error("'%s' must not contain any NA values", name);
    }
  }
  if (min != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] < min) {
        Rf_error("Expected '%s' to be at least %g", name, min);
      }
    }
  }
  if (max != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] > max) {
        Rf_error("Expected '%s' to be at most %g", name, max);
      }
    }
  }
}
void user_check_values_int(int * value, size_t len,
                               double min, double max, const char *name) {
  for (size_t i = 0; i < len; ++i) {
    if (ISNA(value[i])) {
      Rf_error("'%s' must not contain any NA values", name);
    }
  }
  if (min != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] < min) {
        Rf_error("Expected '%s' to be at least %g", name, min);
      }
    }
  }
  if (max != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] > max) {
        Rf_error("Expected '%s' to be at most %g", name, max);
      }
    }
  }
}
void user_check_values(SEXP value, double min, double max,
                           const char *name) {
  size_t len = (size_t)length(value);
  if (TYPEOF(value) == INTSXP) {
    user_check_values_int(INTEGER(value), len, min, max, name);
  } else {
    user_check_values_double(REAL(value), len, min, max, name);
  }
}
SEXP user_list_element(SEXP list, const char *name) {
  SEXP ret = R_NilValue, names = getAttrib(list, R_NamesSymbol);
  for (int i = 0; i < length(list); ++i) {
    if (strcmp(CHAR(STRING_ELT(names, i)), name) == 0) {
      ret = VECTOR_ELT(list, i);
      break;
    }
  }
  return ret;
}
void odin_set_dim(SEXP target, int rank, ...) {
  SEXP r_dim = PROTECT(allocVector(INTSXP, rank));
  int *dim = INTEGER(r_dim);

  va_list ap;
  va_start(ap, rank);
  for (size_t i = 0; i < (size_t)rank; ++i) {
    dim[i] = va_arg(ap, int);
  }
  va_end(ap);

  setAttrib(target, R_DimSymbol, r_dim);
  UNPROTECT(1);
}
void* user_get_array_dim(SEXP user, bool is_integer, void * previous,
                         const char *name, int rank,
                         double min, double max, int *dest_dim) {
  SEXP el = user_get_array_check_rank(user, name, rank, previous == NULL);
  if (el == R_NilValue) {
    return previous;
  }

  dest_dim[0] = LENGTH(el);
  if (rank > 1) {
    SEXP r_dim = PROTECT(coerceVector(getAttrib(el, R_DimSymbol), INTSXP));
    int *dim = INTEGER(r_dim);

    for (size_t i = 0; i < (size_t) rank; ++i) {
      dest_dim[i + 1] = dim[i];
    }

    UNPROTECT(1);
  }

  el = PROTECT(user_get_array_check(el, is_integer, name, min, max));

  int len = LENGTH(el);
  void *dest = NULL;
  if (is_integer) {
    dest = R_Calloc(len, int);
    memcpy(dest, INTEGER(el), len * sizeof(int));
  } else {
    dest = R_Calloc(len, double);
    memcpy(dest, REAL(el), len * sizeof(double));
  }
  R_Free(previous);

  UNPROTECT(1);

  return dest;
}
void* user_get_array(SEXP user, bool is_integer, void * previous,
                     const char *name, double min, double max,
                     int rank, ...) {
  SEXP el = user_get_array_check_rank(user, name, rank, previous == NULL);
  if (el == R_NilValue) {
    return previous;
  }

  SEXP r_dim;
  int *dim;

  size_t len = LENGTH(el);
  if (rank == 1) {
    r_dim = PROTECT(ScalarInteger(len));
  } else {
    r_dim = PROTECT(coerceVector(getAttrib(el, R_DimSymbol), INTSXP));
  }
  dim = INTEGER(r_dim);

  va_list ap;
  va_start(ap, rank);
  for (size_t i = 0; i < (size_t) rank; ++i) {
    int dim_expected = va_arg(ap, int);
    if (dim[i] != dim_expected) {
      va_end(ap); // avoid a leak
      if (rank == 1) {
        Rf_error("Expected length %d value for '%s'", dim_expected, name);
      } else {
        Rf_error("Incorrect size of dimension %d of '%s' (expected %d)",
                 (int)i + 1, name, dim_expected);
      }
    }
  }
  va_end(ap);
  UNPROTECT(1);

  el = PROTECT(user_get_array_check(el, is_integer, name, min, max));

  void *dest = NULL;
  if (is_integer) {
    dest = R_Calloc(len, int);
    memcpy(dest, INTEGER(el), len * sizeof(int));
  } else {
    dest = R_Calloc(len, double);
    memcpy(dest, REAL(el), len * sizeof(double));
  }
  R_Free(previous);

  UNPROTECT(1);

  return dest;
}
SEXP user_get_array_check(SEXP el, bool is_integer, const char *name,
                          double min, double max) {
  size_t len = (size_t) length(el);
  if (is_integer) {
    if (TYPEOF(el) == INTSXP) {
      user_check_values_int(INTEGER(el), len, min, max, name);
    } else if (TYPEOF(el) == REALSXP) {
      el = PROTECT(coerceVector(el, INTSXP));
      user_check_values_int(INTEGER(el), len, min, max, name);
      UNPROTECT(1);
    } else {
      Rf_error("Expected a integer value for '%s'", name);
    }
  } else {
    if (TYPEOF(el) == INTSXP) {
      el = PROTECT(coerceVector(el, REALSXP));
      user_check_values_double(REAL(el), len, min, max, name);
      UNPROTECT(1);
    } else if (TYPEOF(el) == REALSXP) {
      user_check_values_double(REAL(el), len, min, max, name);
    } else {
      Rf_error("Expected a numeric value for '%s'", name);
    }
  }
  return el;
}
SEXP user_get_array_check_rank(SEXP user, const char *name, int rank,
                               bool required) {
  SEXP el = user_list_element(user, name);
  if (el == R_NilValue) {
    if (required) {
      Rf_error("Expected a value for '%s'", name);
    }
  } else {
    if (rank == 1) {
      if (isArray(el)) {
        Rf_error("Expected a numeric vector for '%s'", name);
      }
    } else {
      SEXP r_dim = getAttrib(el, R_DimSymbol);
      if (r_dim == R_NilValue || LENGTH(r_dim) != rank) {
        if (rank == 2) {
          Rf_error("Expected a numeric matrix for '%s'", name);
        } else {
          Rf_error("Expected a numeric array of rank %d for '%s'", rank, name);
        }
      }
    }
  }
  return el;
}
void interpolate_check_y(size_t nx, size_t ny, size_t i, const char *name_arg, const char *name_target) {
  if (nx != ny) {
    if (i == 0) {
      // vector case
      Rf_error("Expected %s to have length %d (for '%s')",
               name_arg, (int)nx, name_target);
    } else {
      // array case
      Rf_error("Expected dimension %d of %s to have size %d (for '%s')",
               (int)i, name_arg, (int)nx, name_target);
    }
  }
}
double odin_sum1(double *x, size_t from, size_t to) {
  double tot = 0.0;
  for (size_t i = from; i < to; ++i) {
    tot += x[i];
  }
  return tot;
}
int odin_isum1(int *x, size_t from, size_t to) {
  int tot = 0.0;
  for (size_t i = from; i < to; ++i) {
    tot += x[i];
  }
  return tot;
}
double scalar_real(SEXP x, const char * name) {
  if (Rf_length(x) != 1) {
    Rf_error("Expected a scalar for '%s'", name);
  }
  double ret = 0.0;
  if (TYPEOF(x) == INTSXP) {
    ret = INTEGER(x)[0];
  } else if (TYPEOF(x) == REALSXP) {
    ret = REAL(x)[0];
  } else {
    Rf_error("Expected a numeric value for '%s'", name);
  }
  return ret;
}
double odin_sum2(double* x, int from_i, int to_i, int from_j, int to_j, int dim_x_1) {
  double tot = 0.0;
  for (int j = from_j; j < to_j; ++j) {
    int jj = j * dim_x_1;
    for (int i = from_i; i < to_i; ++i) {
      tot += x[i + jj];
    }
  }
  return tot;
}
double odin_sum3(double* x, int from_i, int to_i, int from_j, int to_j, int from_k, int to_k, int dim_x_1, int dim_x_12) {
  double tot = 0.0;
  for (int k = from_k; k < to_k; ++k) {
    int kk = k * dim_x_12;
    for (int j = from_j; j < to_j; ++j) {
      int jj = j * dim_x_1 + kk;
      for (int i = from_i; i < to_i; ++i) {
        tot += x[i + jj];
      }
    }
  }
  return tot;
}
// This construction is to help odin
#ifndef CINTERPOLTE_CINTERPOLATE_H_
#endif


void * cinterpolate_alloc(const char *type, size_t n, size_t ny,
                          double *x, double *y, bool fail_on_extrapolate,
                          bool auto_clean) {
  typedef void* interpolate_alloc_t(const char *, size_t, size_t,
                                    double*, double*, bool, bool);
  static interpolate_alloc_t *fun;
  if (fun == NULL) {
    fun = (interpolate_alloc_t*)
      R_GetCCallable("cinterpolate", "interpolate_alloc");
  }
  return fun(type, n, ny, x, y, fail_on_extrapolate, auto_clean);
}


int cinterpolate_eval(double x, void *obj, double *y) {
  typedef int interpolate_eval_t(double, void*, double*);
  static interpolate_eval_t *fun;
  if (fun == NULL) {
    fun = (interpolate_eval_t*)
      R_GetCCallable("cinterpolate", "interpolate_eval");
  }
  return fun(x, obj, y);
}


void cinterpolate_free(void *obj) {
  typedef int interpolate_free_t(void*);
  static interpolate_free_t *fun;
  if (fun == NULL) {
    fun = (interpolate_free_t*)
      R_GetCCallable("cinterpolate", "interpolate_free");
  }
  fun(obj);
}
