## Automatically generated by odin 1.5.11 - do not edit
vaccine_simplified_multiloc_ <- R6::R6Class(
  "odin_model",
  cloneable = FALSE,

  private = list(
    ptr = NULL,
    use_dde = NULL,

    odin = NULL,
    variable_order = NULL,
    output_order = NULL,
    n_out = NULL,
    ynames = NULL,
    interpolate_t = NULL,
    cfuns = list(
      rhs_dde = "vaccine_simplified_multiloc_rhs_dde",
      rhs_desolve = "vaccine_simplified_multiloc_rhs_desolve",
      initmod_desolve = "vaccine_simplified_multiloc_initmod_desolve",
      output_dde = "vaccine_simplified_multiloc_output_dde"),
    dll = "nimue",
    user = c("beta_set", "D_0", "E_0", "gamma_E", "gamma_ICase",
             "gamma_IHosp", "gamma_IMild", "gamma_vaccine", "ICase_0",
             "IHosp_0", "IMild_0", "max_vaccine_set", "mix_mat_set", "N_age",
             "N_locations", "N_prioritisation_steps", "N_vaccine",
             "pi_travel_flight", "pi_travel_non_flight", "prob_death_hosp",
             "prob_hosp", "q_flight", "q_non_flight", "R_0",
             "rel_infectiousness", "rel_infectiousness_vaccinated", "S_0",
             "tt_beta", "tt_vaccine", "vaccine_coverage_mat",
             "vaccine_efficacy_infection"),

    ## This is never called, but is used to ensure that R finds our
    ## symbols that we will use from the package; without this they
    ## cannot be found by dynamic lookup now that we use the package
    ## FFI registration system.
    registration = function() {
      if (FALSE) {
        .C("vaccine_simplified_multiloc_rhs_dde", package = "nimue")
        .C("vaccine_simplified_multiloc_rhs_desolve", package = "nimue")
        .C("vaccine_simplified_multiloc_initmod_desolve", package = "nimue")
        .C("vaccine_simplified_multiloc_output_dde", package = "nimue")
      }
    },

    ## This only does something in delay models
    set_initial = function(t, y, use_dde) {
      .Call("vaccine_simplified_multiloc_set_initial", private$ptr, t, y, use_dde,
            PACKAGE= "nimue")
    },

    update_metadata = function() {
      meta <- .Call("vaccine_simplified_multiloc_metadata", private$ptr,
                    PACKAGE = "nimue")
      private$variable_order <- meta$variable_order
      private$output_order <- meta$output_order
      private$n_out <- meta$n_out
      private$ynames <- private$odin$make_names(
        private$variable_order, private$output_order, FALSE)
      private$interpolate_t <- meta$interpolate_t
    }
  ),

  public = list(
    initialize = function(..., user = list(...), use_dde = FALSE,
                          unused_user_action = NULL) {
      private$odin <- asNamespace("odin")
      private$ptr <- .Call("vaccine_simplified_multiloc_create", user, PACKAGE = "nimue")
      self$set_user(user = user, unused_user_action = unused_user_action)
      private$use_dde <- use_dde
      private$update_metadata()
    },

    ir = function() {
      path_ir <- system.file("odin/vaccine_simplified_multiloc.json", mustWork = TRUE,
                             package = "nimue")
      json <- readLines(path_ir)
      class(json) <- "json"
      json
    },

    ## Do we need to have the user-settable args here? It would be
    ## nice, but that's not super straightforward to do.
    set_user = function(..., user = list(...), unused_user_action = NULL) {
      private$odin$support_check_user(user, private$user, unused_user_action)
      .Call("vaccine_simplified_multiloc_set_user", private$ptr, user, PACKAGE = "nimue")
      private$update_metadata()
    },

    ## This might be time sensitive and, so we can avoid computing
    ## it. I wonder if that's an optimisation we should drop for now
    ## as it does not seem generally useful. This would bring us
    ## closer to the js version which requires that we always pass the
    ## time in.
    initial = function(t) {
      .Call("vaccine_simplified_multiloc_initial_conditions", private$ptr, t, PACKAGE = "nimue")
    },

    rhs = function(t, y) {
      .Call("vaccine_simplified_multiloc_rhs_r", private$ptr, t, y, PACKAGE = "nimue")
    },

    deriv = function(t, y) {
      self$rhs(t, y)
    },

    contents = function() {
      .Call("vaccine_simplified_multiloc_contents", private$ptr, PACKAGE = "nimue")
    },

    transform_variables = function(y) {
      private$odin$support_transform_variables(y, private)
    },

    engine = function() {
      "c"
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      private$odin$wrapper_run_ode(
        self, private, t, y, ..., use_names = use_names)
    }
  ))


vaccine_simplified_multiloc <- function(..., user = list(...), use_dde = FALSE,
                     unused_user_action = NULL) {
  asNamespace("odin")$deprecated_constructor_call("vaccine_simplified_multiloc")
  vaccine_simplified_multiloc_$new(user = user, use_dde = use_dde,
                unused_user_action = unused_user_action)
}
class(vaccine_simplified_multiloc) <- "odin_generator"
attr(vaccine_simplified_multiloc, "generator") <- vaccine_simplified_multiloc_
